const WORD_FAMILIES = {
  core: ["CAT","NIGHT","CAKE","RING","BOAT","BEAR","TRAIN","CLOCK","STAR","CHAIR","BLUE","BONE","SAND","DOG","TREE","SUN","MOON","FISH","DUCK","PEN","CUP","BED","PIG","FOX","HOUSE","CAR","DOOR","BOOK","GAME","BALL","FIRE","GOLD","ICE","SNOW","WIND","CLOUD","RAIN","STORM","WAVE","HILL","ROCK","ROAD","PATH","BRIDGE","TOWN","STREET","PARK","SHOP","FARM","BARN","BIRD","COW","HORSE","SHEEP","GOAT","DEER","WOLF","SNAKE","FROG","CRAB","WHALE","SHARK","SEAL","BEE","ANT","FLY","WORM","SPIDER","EYE","NOSE","EAR","MOUTH","HAND","FOOT","LEG","ARM","HEART","MIND","TIME","DAY","WEEK","MONTH","YEAR","SPRING","SUMMER","FALL","WINTER","MORNING","NOON","EVENING","DAWN","DUSK","RED","GREEN","YELLOW","BLACK","WHITE","GRAY"],
  longWords: ["ABDOMEN","ASTRONAUT","BICYCLE","BUTTERFLY","CALENDAR","CHOCOLATE","DIAMOND","ELEPHANT","FESTIVAL","GALAXY","HARMONY","HORIZON","INSTRUMENT","JUNGLE","KANGAROO","LAVENDER","MICROSCOPE","NECTAR","OXYGEN","PENGUIN","QUARTER","RADIATOR","SYMPHONY","TELESCOPE","UMBRELLA","VOLCANO","WATERFALL","XYLOPHONE","YOGURT","ZEPPELIN","ACADEMY","BACTERIA","CABINET","DAFFODIL","ECONOMY","FACTORY","GEOMETRY","HELICOPTER","ILLUSION","JOURNAL","KEYBOARD","LABORATORY","MACHINERY","NOVELIST","ORCHESTRA","PARACHUTE","QUADRANT","REPTILE","SATELLITE","THERMOMETER","UNIVERSE","VACUUM","WILDERNESS","YACHT","ZOOLOGY","ALGEBRA","BROCCOLI","CAPITAL","DINOSAUR","ELEVATOR","FURNITURE","GOVERNOR","HOSPITAL","INVENTOR","JUSTICE","KINETIC","LIBRARY","MONUMENT","NARRATIVE","OASIS","PYRAMID","QUESTION","RESTAURANT","STADIUM","TRIANGLE","UTENSIL","VEHICLE","WEATHER","YIELD","ZEBRA","ARCHITECT","BALCONY","CAMERA","DOCUMENT","ENVELOPE","FEATHER","GALLERY","HERITAGE","ISLAND","JACKET","KITCHEN","LUGGAGE","MEDICINE","NETWORK","OFFICER","PASSENGER","QUALITY","RECIPE","SCIENTIST","TEACHER"],
  AT:   ["BAT","HAT","MAT","RAT","CHAT","FLAT","SPAT","SCAT","SLAT","GNAT","BRAT","VAT","DRAT","SAT","FAT","PAT","COMBAT","ACROBAT","FORMAT","HABITAT","DIPLOMAT","DOORMAT","MUSKRAT","WOMBAT","LARIAT","STAT","THAT","SPLAT"],
  AY:   ["PLAY","STAY","TRAY","SPRAY","CLAY","PRAY","SWAY","AWAY","DELAY","BETRAY","DISPLAY","RUNWAY","HIGHWAY","SUBWAY","DRIVEWAY","GATEWAY","HOLIDAY","BIRTHDAY","MONDAY","SUNDAY","PAYDAY","HOORAY","OKAY","RELAY","DECAY","ESSAY","HALFWAY","ANYWAY","FREEWAY","MIDWAY","SEAWAY","ARRAY","MAYDAY","REPLAY","XRAY"],
  EE:   ["FREE","THREE","KNEE","AGREE","DEGREE","DECREE","REFEREE","JUBILEE","GUARANTEE","EMPLOYEE","TRAINEE","CHIMPANZEE","COFFEE","TOFFEE","PEDIGREE","CHICKADEE","JAMBOREE","OVERSEE","DISAGREE","PUREE","DUNGAREE","GLEE","SPREE","GHEE","GOATEE","MATINEE","NOMINEE","MARQUEE","MANATEE"],
  IGHT: ["LIGHT","FLIGHT","FRIGHT","BRIGHT","SIGHT","TIGHT","MIGHT","RIGHT","KNIGHT","PLIGHT","SLIGHT","DELIGHT","INSIGHT","MIDNIGHT","SUNLIGHT","MOONLIGHT","TONIGHT","TWILIGHT","HIGHLIGHT","SPOTLIGHT","FORESIGHT","OVERSIGHT","DAYLIGHT","STARLIGHT","LAMPLIGHT","LIMELIGHT","OUTRIGHT","UPRIGHT","AIRTIGHT","COPYRIGHT"],
  AKE:  ["LAKE","MAKE","TAKE","WAKE","RAKE","SHAKE","BRAKE","FLAKE","STAKE","DRAKE","QUAKE","MISTAKE","AWAKE","HANDSHAKE","EARTHQUAKE","MILKSHAKE","CUPCAKE","PANCAKE","NAMESAKE","SWEEPSTAKE","RATTLESNAKE","OPAQUE","PARTAKE","INTAKE","OUTTAKE","REMAKE"],
  ING:  ["SING","KING","WING","THING","STRING","BRING","CLING","FLING","SWING","STING","WRING","ANYTHING","EVERYTHING","NOTHING","SOMETHING","DARLING","BOWSTRING","HAMSTRING","OFFSPRING","ZING","BLING","SLING","YEARLING"],
  OWN:  ["BROWN","CLOWN","CROWN","DROWN","FROWN","GOWN","RENOWN","DOWNTOWN","MIDTOWN","UPTOWN","HOMETOWN","NIGHTGOWN"],
  ORE:  ["MORE","SHORE","STORE","SNORE","SCORE","CHORE","SWORE","ADORE","EXPLORE","IGNORE","BEFORE","RESTORE","ENCORE","FOLKLORE","SEASHORE","OFFSHORE","GALORE","CARNIVORE","HERBIVORE","SYCAMORE","ANYMORE","THEREFORE"],
  INE:  ["LINE","VINE","SHINE","SPINE","TWINE","WHINE","DIVINE","SUNSHINE","PORCUPINE","VALENTINE","TANGERINE","SUBMARINE","MAGAZINE","TRAMPOLINE","QUARANTINE","DISCIPLINE","GASOLINE","GUIDELINE","HEADLINE","OUTLINE","BEELINE","AIRLINE","DEADLINE"],
  UG:   ["BUG","HUG","JUG","MUG","RUG","TUG","LUG","PLUG","DRUG","SHRUG","SNUG","THUG","LADYBUG","HUMBUG","FIREBUG","JITTERBUG"],
  OT:   ["HOT","POT","DOT","LOT","NOT","ROT","COT","JOT","KNOT","PLOT","SLOT","SPOT","SHOT","TROT","BLOT","CLOT","APRICOT","MASCOT","ROBOT","TEAPOT","JACKPOT","PARROT","CARROT"],
  ARK:  ["DARK","BARK","MARK","SPARK","STARK","LARK","REMARK","LANDMARK","EARMARK","BENCHMARK","TRADEMARK"],
  ELL:  ["BELL","SELL","TELL","WELL","SHELL","SMELL","SPELL","SWELL","YELL","DWELL","FAREWELL","BLUEBELL","DOORBELL","SEASHELL","EGGSHELL","COWBELL"],
  ICK:  ["STICK","BRICK","CHICK","CLICK","FLICK","KICK","LICK","NICK","PICK","QUICK","SICK","THICK","TICK","TRICK","WICK","CANDLESTICK","LIPSTICK","YARDSTICK","HOMESICK","SLAPSTICK"],
  OOM:  ["ROOM","BROOM","BLOOM","GLOOM","GROOM","ZOOM","BOOM","LOOM","DOOM","MUSHROOM","BEDROOM","CLASSROOM","BALLROOM","HEIRLOOM"],
  AME:  ["NAME","FAME","FLAME","FRAME","BLAME","SHAME","TAME","NICKNAME","BECAME","INFLAME"],
  EAK:  ["PEAK","LEAK","SPEAK","STREAK","CREAK","SNEAK","SQUEAK","TWEAK","BLEAK","OUTBREAK"],
  OUSE: ["MOUSE","BLOUSE","GROUSE","SPOUSE","CLUBHOUSE","DOGHOUSE","GREENHOUSE","LIGHTHOUSE","WAREHOUSE","BIRDHOUSE"],
  AIN:  ["BRAIN","CHAIN","PLAIN","STAIN","MAIN","GAIN","PAIN","DRAIN","SPRAIN","COMPLAIN","EXPLAIN","CONTAIN","REMAIN","REFRAIN","TERRAIN","DOMAIN","CAMPAIGN"],
  OUD:  ["LOUD","PROUD","CROWD","SHROUD","ALOUD"],
  ILL:  ["BILL","CHILL","DRILL","FILL","GRILL","KILL","MILL","PILL","SKILL","SPILL","STILL","THRILL","WILL","QUILL","GILL","DILL","UPHILL","WINDMILL","ANTHILL"],
  UNK:  ["TRUNK","SKUNK","CHUNK","DRUNK","FLUNK","JUNK","PLUNK","PUNK","SHRUNK","SPUNK","SUNK","BUNK"],
  ASH:  ["FLASH","CRASH","SPLASH","TRASH","CASH","DASH","GASH","HASH","MASH","RASH","SASH","SLASH","SMASH","STASH","CLASH","EYELASH","BACKLASH"],
  EED:  ["SEED","FEED","WEED","GREED","BREED","CREED","FREED","NEED","SPEED","TWEED","INDEED","PROCEED","EXCEED","SUCCEED"],
  OLD:  ["BOLD","COLD","FOLD","HOLD","MOLD","SCOLD","SOLD","TOLD","UNTOLD","HOUSEHOLD","THRESHOLD","STRONGHOLD","MARIGOLD","FOOTHOLD"],
  ORN:  ["BORN","CORN","HORN","MORN","THORN","TORN","WORN","ACORN","POPCORN","UNICORN","ADORN","NEWBORN","LONGHORN"],
  UMP:  ["BUMP","DUMP","HUMP","JUMP","LUMP","PUMP","STUMP","TRUMP","CHUMP","CLUMP","GRUMP","PLUMP","THUMP"],
  UCK:  ["BUCK","LUCK","MUCK","PUCK","STUCK","STRUCK","TRUCK","TUCK","CLUCK","CHUCK","PLUCK","SHUCK"],
  UST:  ["BUST","DUST","GUST","RUST","TRUST","CRUST","ADJUST","ROBUST","SAWDUST","STARDUST","MISTRUST","DISGUST"],
  UTE:  ["CUTE","FLUTE","MUTE","CHUTE","BRUTE","SALUTE","DISPUTE","COMPUTE","TRIBUTE","MINUTE","INSTITUTE","ATTRIBUTE"],
  AB:   ["CAB","DAB","GAB","GRAB","JAB","LAB","NAB","SCAB","SLAB","STAB","TAB"],
  AG:   ["BAG","DRAG","FLAG","GAG","LAG","NAG","RAG","SAG","SHAG","SNAG","STAG","TAG","WAG","ZIGZAG","HANDBAG","SANDBAG"],
  AN:   ["BAN","CAN","FAN","MAN","PAN","PLAN","RAN","SCAN","SPAN","TAN","VAN","CLAN","SUNTAN","PELICAN","ORPHAN"],
  AP:   ["CAP","CLAP","FLAP","GAP","LAP","MAP","NAP","RAP","SAP","SLAP","SNAP","STRAP","TAP","TRAP","WRAP","ZAP","MISHAP","MOUSETRAP","HANDICAP"],
  AW:   ["CLAW","DRAW","FLAW","GNAW","JAW","LAW","PAW","RAW","SAW","STRAW","THAW","JIGSAW","SEESAW","OUTLAW","COLESLAW"],
  AZE:  ["BLAZE","CRAZE","DAZE","GAZE","GLAZE","GRAZE","HAZE","MAZE","PHASE","AMAZE"],
  EAT:  ["BEAT","CHEAT","HEAT","MEAT","NEAT","SEAT","TREAT","WHEAT","DEFEAT","REPEAT","RETREAT","HEARTBEAT"],
  END:  ["BEND","BLEND","FRIEND","LEND","MEND","SEND","SPEND","TEND","TREND","AMEND","DEFEND","WEEKEND","BOYFRIEND","GIRLFRIEND","APPEND","OFFEND"],
  ENT:  ["BENT","DENT","RENT","TENT","CENT","SCENT","SPENT","WENT","ACCENT","CEMENT","MOMENT","STUDENT","ARGUMENT","PRESENT","PERCENT"],
  EST:  ["BEST","CHEST","GUEST","NEST","PEST","REST","TEST","VEST","WEST","ZEST","REQUEST","PROTEST","CONTEST","HARVEST","INTEREST"],
  OSE:  ["ROSE","CHOSE","CLOSE","HOSE","POSE","THOSE","AROSE","COMPOSE","PROPOSE","SUPPOSE","EXPOSE"],
  OKE:  ["JOKE","POKE","SMOKE","CHOKE","BROKE","STROKE","SPOKE","AWOKE","ARTICHOKE","BACKSTROKE"],
  OLE:  ["HOLE","MOLE","POLE","ROLE","SOLE","STOLE","WHOLE","CONSOLE","TADPOLE","CASSEROLE"],
  ONE:  ["CONE","TONE","ZONE","PHONE","STONE","ALONE","THRONE","DRONE","OZONE","BACKBONE","TELEPHONE","SAXOPHONE","MEGAPHONE"],
  IRE:  ["HIRE","TIRE","WIRE","SPIRE","ADMIRE","INSPIRE","ENTIRE","VAMPIRE","CAMPFIRE","BONFIRE","EMPIRE"],
  EAR:  ["FEAR","HEAR","NEAR","DEAR","CLEAR","SPEAR","APPEAR","CAREER","ATMOSPHERE","ENGINEER","VOLUNTEER","DISAPPEAR","PIONEER","SOUVENIR","REINDEER","MUSKETEER"],
  AIR:  ["AIR","FAIR","HAIR","PAIR","STAIR","DESPAIR","REPAIR","AFFAIR"],
  ARE:  ["CARE","DARE","RARE","BARE","MARE","SCARE","SHARE","SPARE","SQUARE","AWARE","BEWARE","NIGHTMARE","SOFTWARE","HARDWARE","WELFARE","HEALTHCARE"],
  OY:   ["BOY","TOY","JOY","EMPLOY","ENJOY","DESTROY","ANNOY","CONVOY","COWBOY","TOMBOY","CORDUROY"],
  OIN:  ["COIN","JOIN","GROIN","SIRLOIN"],
  OUT:  ["OUT","SHOUT","SCOUT","TROUT","SPOUT","SPROUT","WITHOUT","LAYOUT","WORKOUT","LOOKOUT","BLACKOUT","DROPOUT","HANGOUT","SHOOTOUT","CHECKOUT"],
  OWL:  ["OWL","HOWL","GROWL","PROWL","SCOWL"],
  ORT:  ["SHORT","SPORT","COURT","FORT","SORT","PORT","SNORT","RESORT","SUPPORT","PASSPORT","AIRPORT","REPORT","TRANSPORT","IMPORT","EXPORT"],
  ARM2: ["CHARM","ALARM","HARM","DISARM"],
  ARD:  ["CARD","HARD","YARD","GUARD","REGARD","BACKYARD","STANDARD","BOULEVARD"],
  ANCE: ["DANCE","CHANCE","GLANCE","TRANCE","ADVANCE","ROMANCE","ENTRANCE","FINANCE","DISTANCE","INSTANCE"],
  ANT2: ["PANT","CHANT","GRANT","PLANT","SLANT","INSTANT","ASSISTANT","IMPORTANT","ELEGANT","DISTANT","CONSTANT"],
  ANK:  ["BANK","RANK","TANK","BLANK","CRANK","DRANK","FRANK","PLANK","PRANK","SANK","SPANK","THANK","SHRANK"],
  AMP:  ["CAMP","DAMP","LAMP","RAMP","STAMP","TRAMP","CLAMP","CRAMP","CHAMP","SCAMP"],
  AND2: ["BAND","LAND","GRAND","STAND","BRAND","STRAND","UNDERSTAND","COMMAND","DEMAND","WONDERLAND","HEADBAND","WRISTBAND"],
  ANG:  ["BANG","GANG","HANG","RANG","SANG","SLANG","CLANG","FANG","TWANG","BOOMERANG","MUSTANG"],
  ONG:  ["SONG","LONG","STRONG","WRONG","GONG","PRONG","ALONG","BELONG","LIFELONG"],
  OSS:  ["BOSS","LOSS","MOSS","TOSS","CROSS","FLOSS","ACROSS","ALBATROSS"],
  OFF:  ["SCOFF","TAKEOFF","KICKOFF","STANDOFF","PLAYOFF","LIFTOFF"],
  INK:  ["PINK","SINK","THINK","BLINK","BRINK","CLINK","DRINK","LINK","MINK","RINK","STINK","WINK","SHRINK"],
  UM:   ["DRUM","GUM","HUM","PLUM","SUM","THUMB","DUMB","NUMB","CRUMB","ALBUM"],
  ICE2: ["DICE","MICE","NICE","PRICE","RICE","SLICE","SPICE","TWICE","ADVICE","DEVICE","SACRIFICE","PARADISE"],
  OICE: ["CHOICE","VOICE","REJOICE","INVOICE"],
  AUGHT:["CAUGHT","TAUGHT","BOUGHT","THOUGHT","FOUGHT","SOUGHT","BROUGHT","NAUGHT"],
  ALK:  ["WALK","TALK","CHALK","STALK"],
  AWK:  ["HAWK","SQUAWK","TOMAHAWK"],
  IRT:  ["SHIRT","SKIRT","DIRT","FLIRT","HURT"],
  URN:  ["TURN","BURN","LEARN","EARN","FERN","CHURN","RETURN","STERN","CONCERN"],
  URSE: ["NURSE","PURSE","CURSE","WORSE","VERSE","REVERSE","CONVERSE"],
  OON:  ["SOON","SPOON","BALLOON","CARTOON","RACCOON","COCOON","LAGOON","MAROON","MONSOON","HARPOON","TYPHOON"],
  OOL:  ["COOL","FOOL","POOL","SCHOOL","SPOOL","STOOL","TOOL","CARPOOL","WHIRLPOOL"],
  OOT:  ["BOOT","ROOT","SCOOT","SHOOT","LOOT"],
  OOF:  ["ROOF","HOOF","PROOF","SPOOF","ALOOF","WATERPROOF","FIREPROOF"],
  OWER: ["FLOWER","SHOWER","POWER","TOWER","COWER"],
  OUR:  ["HOUR","SOUR","FLOUR"],
  IDE:  ["RIDE","SIDE","WIDE","BRIDE","GLIDE","GUIDE","HIDE","PRIDE","SLIDE","TIDE","DECIDE","DIVIDE","PROVIDE","OUTSIDE","WORLDWIDE","LANDSLIDE","SEASIDE"],
  ITE:  ["BITE","KITE","SITE","QUITE","WRITE","INVITE","IGNITE","UNITE","DYNAMITE","APPETITE"],
  IPE:  ["PIPE","WIPE","RIPE","GRIPE","STRIPE","SWIPE","TYPE"],
  IVE:  ["FIVE","DIVE","DRIVE","HIVE","THRIVE","ALIVE","ARRIVE","SURVIVE"],
  IZE:  ["SIZE","PRIZE","RISE","WISE","SURPRISE","DISGUISE","EXERCISE","ADVISE","OTHERWISE"],
  OPE:  ["HOPE","ROPE","SLOPE","SCOPE","SOAP","ANTELOPE","PERISCOPE"],
  OAT:  ["COAT","FLOAT","MOAT","THROAT","OAT","BLOAT","GLOAT"],
  UBBLE:["BUBBLE","TROUBLE","DOUBLE","RUBBLE","STUBBLE"],
  ITTLE:["LITTLE","BRITTLE","WHITTLE"],
  IDDLE:["RIDDLE","MIDDLE","FIDDLE","GRIDDLE"],
  UDDLE:["PUDDLE","CUDDLE","HUDDLE","MUDDLE"],
  ACKET:["RACKET","BRACKET","PACKET"],
  ATTER:["BATTER","MATTER","CHATTER","SCATTER","LATTER","FLATTER","SHATTER","SPLATTER"],
  UTTER:["BUTTER","GUTTER","MUTTER","SHUTTER","STUTTER","CLUTTER","FLUTTER"],
  UTTON:["BUTTON","MUTTON","GLUTTON"],
  OCKET:["ROCKET","POCKET","SOCKET","LOCKET","DOCKET"],
  ANDY: ["CANDY","SANDY","HANDY","BRANDY","DANDY"],
  IGGLE:["GIGGLE","WIGGLE","JIGGLE","WRIGGLE","SQUIGGLE"],
  OODLE:["NOODLE","POODLE","DOODLE"],
  UMBLE:["TUMBLE","MUMBLE","RUMBLE","GRUMBLE","STUMBLE","CRUMBLE","JUMBLE","HUMBLE"],
  ANGLE:["TANGLE","JANGLE","WRANGLE","RECTANGLE"],
  INGLE:["JINGLE","SINGLE","TINGLE","MINGLE","SHINGLE"],
  ICKLE:["TICKLE","PICKLE","TRICKLE","PRICKLE","FICKLE"],
  ELLOW:["MELLOW","FELLOW","BELLOW","HELLO"],
  ALLOW:["SHALLOW","CALLOW","WALLOW","SWALLOW"],
  OLLOW:["FOLLOW","HOLLOW"],
  ARDEN:["GARDEN","HARDEN"],
  OTTLE:["BOTTLE","THROTTLE"],
  ISTLE:["WHISTLE","THISTLE","BRISTLE"],
  USTLE:["BUSTLE","HUSTLE","RUSTLE","MUSCLE"],
  ABLE: ["TABLE","CABLE","FABLE","STABLE","UNABLE"]
};
const WORD_BANK = Array.from(new Set(Object.values(WORD_FAMILIES).flat()));
const QUALITY_WORDS = Array.from(new Set([...WORD_FAMILIES.core, ...Object.keys(WORD_FAMILIES)
  .filter(k => k !== 'core' && k !== 'longWords')
  .flatMap(k => WORD_FAMILIES[k])]));


const RECENT_TARGET_LIMIT = 18;
const RECENT_FAMILY_LIMIT = 5;
const wordToFamilies = new Map();
Object.entries(WORD_FAMILIES).forEach(([family, words]) => {
  if (family === 'core' || family === 'longWords') return;
  words.forEach(word => {
    if (!wordToFamilies.has(word)) wordToFamilies.set(word, []);
    wordToFamilies.get(word).push(family);
  });
});
const CORE_RHYME_FAMILIES = {
  CAT:'AT', NIGHT:'IGHT', CAKE:'AKE', RING:'ING', BOAT:'OAT', BEAR:'AIR',
  TRAIN:'AIN', CHAIR:'AIR', BONE:'ONE', TREE:'EE', MOON:'OON', DUCK:'UCK',
  HOUSE:'OUSE', DOOR:'ORE', GAME:'AME', FIRE:'IRE', GOLD:'OLD', ICE:'ICE2',
  CLOUD:'OUD', RAIN:'AIN', HILL:'ILL', TOWN:'OWN', STORM:'ORM', WAVE:'AVE',
  ROCK:'OCK', CLOCK:'OCK', BALL:'ALL', SUN:'UN', PEN:'EN', BED:'ED'
};
function familyOf(word){
  const upper = word.toUpperCase();
  const families = wordToFamilies.get(upper);
  return families ? families[0] : (CORE_RHYME_FAMILIES[upper] || 'other:' + upper.slice(-3));
}
function loadTargetHistory(){
  try {
    const data = JSON.parse(localStorage.getItem('rhymeMatchTargets') || '{}');
    return { words: Array.isArray(data.words) ? data.words.slice(-RECENT_TARGET_LIMIT) : [], families: Array.isArray(data.families) ? data.families.slice(-RECENT_FAMILY_LIMIT) : [] };
  } catch(e){ return { words:[], families:[] }; }
}
let targetHistory = loadTargetHistory();
function rememberTarget(word){
  const upper = word.toUpperCase();
  targetHistory.words = [...targetHistory.words.filter(w => w !== upper), upper].slice(-RECENT_TARGET_LIMIT);
  targetHistory.families = [...targetHistory.families, familyOf(upper)].slice(-RECENT_FAMILY_LIMIT);
  try { localStorage.setItem('rhymeMatchTargets', JSON.stringify(targetHistory)); } catch(e){}
}
function pickTarget(){
  let choices = QUALITY_WORDS.filter(w => !targetHistory.words.includes(w) && !targetHistory.families.includes(familyOf(w)));
  if (!choices.length) choices = QUALITY_WORDS.filter(w => !targetHistory.words.includes(w));
  if (!choices.length) choices = QUALITY_WORDS;
  return choices[Math.floor(Math.random() * choices.length)];
}
/* Twist challenges are selected only when at least two known rhymes fit. The host
   still judges meaning, syllables and rhyme validity. Unknown custom targets use
   a broad letter rule rather than an unplayable guessed category. */
const TWIST_ONE_SYLLABLE = new Set('BAT HAT RAT PLAY STAY TRAY FREE THREE KNEE LIGHT FLIGHT BRIGHT LAKE MAKE WAKE SING KING WING BROWN CLOWN CROWN MORE SHORE STORE LINE VINE SHINE BUG HUG JUG HOT POT DOT DARK BARK MARK BELL SELL TELL STICK BRICK CHICK ROOM BROOM BLOOM NAME FAME FLAME PEAK LEAK SPEAK MOUSE BLOUSE BRAIN CHAIN PLAIN LOUD PROUD CROWD BILL CHILL DRILL TRUNK SKUNK CHUNK FLASH CRASH SPLASH SEED FEED WEED BOLD COLD FOLD BORN CORN HORN BUMP DUMP JUMP BUCK LUCK TRUCK BUST DUST RUST CUTE FLUTE MUTE CAB DAB GRAB BAG FLAG RAG CAN FAN MAN CAP MAP TAP CLAW JAW PAW BLAZE GAZE MAZE BEAT HEAT MEAT BEND FRIEND SEND TENT RENT WENT BEST REST TEST ROSE HOSE POSE JOKE POKE SMOKE HOLE MOLE POLE CONE PHONE STONE HIRE TIRE WIRE FEAR HEAR NEAR CARE DARE RARE BOY TOY JOY COIN JOIN OUT SHOUT SCOUT OWL HOWL GROWL SHORT SPORT COURT CARD HARD YARD DANCE CHANCE GLANCE BANK TANK BLANK CAMP LAMP RAMP BAND LAND STAND BANG HANG RANG SONG LONG WRONG BOSS LOSS MOSS PINK SINK THINK DRUM GUM HUM DICE MICE NICE WALK TALK CHALK SHIRT SKIRT DIRT TURN BURN EARN NURSE PURSE CURSE SOON SPOON MOON'.split(' '));
const TWIST_TAGS = {
  food:'CAKE CUPCAKE PANCAKE MILKSHAKE STEAK RICE SPICE SLICE MEAT WHEAT TREAT POT TEAPOT CARROT APRICOT CORN POPCORN ACORN GHEE PUREE COFFEE TOFFEE MUSHROOM PLUM GUM',
  animal:'BAT RAT GNAT WOMBAT MUSKRAT DRAKE SNAKE RATTLESNAKE MOUSE GROUSE MOLE TADPOLE DEER REINDEER TROUT OWL HAWK LARK SHARK SKUNK CHICK COW CROW',
  object:'HAT MAT DOORMAT TRAY CLAY RAKE BRAKE STAKE LAMP FRAME BROOM ROOM PHONE STONE BRICK STICK CLOCK SOCK BLOCK BAG FLAG MUG RUG JUG CUP',
  place:'LAKE SHORE STORE PARK LANDMARK ROOM BEDROOM CLASSROOM BALLROOM DOWNTOWN UPTOWN HOMETOWN SEASHORE OFFSHORE AIRPORT PORT COURT FORT',
  job:'KING GROOM REFEREE ENGINEER VOLUNTEER PIONEER OFFICER SCIENTIST TEACHER INVENTOR GOVERNOR NURSE SCOUT',
  nature:'SUNLIGHT MOONLIGHT STARLIGHT DAYLIGHT LAKE FLAME RAIN CLOUD STORM WAVE WIND STAR ROCK TREE SNOW HILL BREEZE THORN DAWN',
  sound:'BELL COWBELL DOORBELL YELL HOWL GROWL SQUEAK CREAK BANG CLANG SONG GONG HUM DRUM BOOM ZING',
  clothing:'HAT COAT GOWN NIGHTGOWN SHIRT SKIRT VEST JACKET SHOES',
  travel:'TRAIN PLANE BOAT ROAD RUNWAY HIGHWAY SUBWAY GATEWAY PASSPORT AIRPORT PORT CAR CAB VAN',
  celebration:'CAKE CUPCAKE BIRTHDAY HOLIDAY HOORAY JUBILEE JAMBOREE PARTY PRESENT GIFT CROWN',
  tiny:'ANT GNAT BUG MICE COIN SEED DICE PEA DOT',
  spooky:'FRIGHT NIGHT MIDNIGHT GLOOM DOOM GHOST VAMPIRE CURSE DARK SHADOW',
  action:'PLAY STAY PRAY SING BRING SWING FLY TRY JUMP BUMP CLAP SNAP RAP TAP DRAW SAW WALK TALK TURN BURN SHOUT',
  feeling:'JOY GLEE DELIGHT FRIGHT SHAME BLAME DESPAIR HOPE LOVE FEAR SCARE GLAD',
  funny:'JOKE CLOWN PRANK GAG WIG GOOF ZING SPLAT BRAT',
  party:'CAKE CUPCAKE PANCAKE MILKSHAKE GAME HAT CROWN GIFT PRESENT JOKE'
};
const TWIST_TAG_LABELS = {
  food:'something edible', animal:'an animal', object:'an object you could use', place:'a place', job:'a job or role', nature:'something from nature', sound:'a sound or something noisy', clothing:'something you could wear', travel:'something linked to travel', celebration:'something at a celebration', tiny:'something tiny', spooky:'something spooky', action:'an action', feeling:'a feeling', funny:'something funny', party:'something you could bring to a party'
};
const TWIST_CHALLENGES = [
  ...Array.from({length:8},(_,i) => ({id:`length-${i+3}`, text:`Use exactly ${i+3} letters.`, test:w => w.length === i+3})),
  {id:'short',text:'Use a short rhyme: 3–5 letters.',test:w => w.length >= 3 && w.length <= 5},
  {id:'long',text:'Use a long rhyme: at least 8 letters.',test:w => w.length >= 8},
  {id:'one-syllable',text:'Use a one-syllable rhyme.',test:w => TWIST_ONE_SYLLABLE.has(w)},
  {id:'verb',text:'Use a verb: something a person can do.',test:w => TWIST_TAGS.action.split(' ').includes(w)},
  {id:'ends-in-s',text:'Use a word ending in S.',test:w => w.endsWith('S') && !w.endsWith('SS')},
  {id:'compound',text:'Use a compound word.',test:w => w.length >= 8 && /(DAY|LIGHT|HOUSE|ROOM|WAY|TIME|LAND|WORD|WORK)/.test(w)},
  ...'AEIOU'.split('').map(letter => ({id:`contains-${letter}`,text:`Use a rhyme containing the letter ${letter}.`,test:w => w.includes(letter)})),
  ...'BCDFGHJKLMNPRSTW'.split('').map(letter => ({id:`starts-${letter}`,text:`Use a rhyme beginning with ${letter}.`,test:w => w.startsWith(letter)})),
  ...Object.entries(TWIST_TAGS).map(([id,words]) => ({id:`category-${id}`,text:`Use ${TWIST_TAG_LABELS[id]}.`,test:w => words.split(' ').includes(w)}))
];
function pickTwistChallenge(target, history){
  const families = wordToFamilies.get(target) || [CORE_RHYME_FAMILIES[target]].filter(Boolean);
  const words = [...new Set(families.flatMap(f => WORD_FAMILIES[f] || []))].filter(w => w !== target);
  let eligible = TWIST_CHALLENGES.filter(challenge => words.filter(challenge.test).length >= 2);
  if (!eligible.length) return { id:'different-first-letter', text:`Use a rhyme that starts with a different letter than ${target}.` };
  const fresh = eligible.filter(challenge => !history.includes(challenge.id));
  if (fresh.length) eligible = fresh;
  const chosen = eligible[Math.floor(Math.random() * eligible.length)];
  return { id:chosen.id, text:chosen.text };
}


export { WORD_FAMILIES, WORD_BANK, QUALITY_WORDS, familyOf, rememberTarget, pickTarget, pickTwistChallenge };
