const f = (easy, medium = '', hard = '') => ({
  easy: easy.split(' ').filter(Boolean),
  medium: medium.split(' ').filter(Boolean),
  hard: hard.split(' ').filter(Boolean)
});

const FAMILY_TIERS = {
  /* ---------------- A ---------------- */
  AT:   f('BAT HAT MAT RAT CAT FAT PAT SAT FLAT CHAT THAT', 'SPLAT BRAT SCAT GNAT TOMCAT VAT', 'ACROBAT DIPLOMAT DOORMAT MUSKRAT HABITAT COPYCAT WOMBAT'),
  AN:   f('CAN FAN MAN PAN RAN VAN TAN PLAN SCAN CLAN BAN', 'SPAN BEGAN OUTRAN SUNTAN TRASHCAN', 'CARAVAN SUPERMAN MARZIPAN'),
  AP:   f('CAP MAP TAP NAP GAP LAP CLAP SNAP TRAP WRAP', 'FLAP SLAP STRAP ZAP CHAP SCRAP', 'MISHAP MOUSETRAP HANDICAP KIDNAP'),
  AG:   f('BAG TAG FLAG WAG NAG RAG DRAG', 'SNAG STAG BRAG SAG SHAG', 'HANDBAG SANDBAG ZIGZAG SCALLYWAG'),
  AB:   f('CRAB GRAB STAB LAB TAB CAB', 'SLAB JAB DAB NAB SCAB FLAB BLAB DRAB', 'TAXICAB'),
  AD:   f('BAD DAD MAD SAD GLAD PAD HAD', 'CLAD FAD LAD PLAID', 'LAUNCHPAD NOTEPAD SKETCHPAD'),
  AM:   f('HAM JAM RAM DAM CLAM SLAM SCAM', 'SPAM TRAM DRAM SHAM SWAM', 'DIAGRAM TELEGRAM ANAGRAM PROGRAM'),
  ACK:  f('BACK PACK SACK TACK RACK BLACK SNACK TRACK CRACK QUACK', 'SHACK STACK SMACK WHACK JACK LACK', 'BACKPACK HAYSTACK THUMBTACK PAPERBACK FLAPJACK'),
  ASH:  f('CASH DASH MASH RASH SASH BASH', 'FLASH CRASH SPLASH TRASH SMASH SLASH CLASH STASH', 'EYELASH BACKLASH SUCCOTASH'),
  ASS:  f('PASS CLASS GLASS GRASS BRASS MASS', 'SASS LASS ALAS', 'BYPASS SURPASS UNDERPASS HOURGLASS'),
  ATCH: f('CATCH MATCH BATCH LATCH PATCH HATCH', 'SCRATCH SNATCH THATCH', 'DISPATCH MISMATCH UNLATCH'),
  ANK:  f('BANK TANK RANK SANK THANK', 'BLANK PLANK FRANK PRANK DRANK SPANK CRANK YANK', 'SHRANK OUTRANK'),
  AND:  f('BAND HAND LAND SAND STAND GRAND BRAND', 'STRAND EXPAND COMMAND DEMAND', 'UNDERSTAND WONDERLAND HEADBAND WRISTBAND QUICKSAND SECONDHAND'),
  ANG:  f('BANG GANG HANG RANG SANG SLANG FANG', 'CLANG TWANG PANG', 'BOOMERANG MUSTANG'),
  ANCE: f('DANCE CHANCE GLANCE', 'TRANCE PRANCE STANCE', 'ADVANCE ENHANCE PERCHANCE ROMANCE'),
  ANT:  f('PANT CHANT GRANT PLANT SLANT RANT', 'SCANT ENCHANT', 'SUPPLANT TRANSPLANT RECANT'),
  ALL:  f('BALL CALL FALL HALL MALL TALL WALL SMALL STALL', 'APPALL INSTALL', 'WATERFALL BASKETBALL OVERALL SNOWBALL'),
  ALT:  f('SALT MALT HALT', 'FAULT VAULT', 'ASSAULT SOMERSAULT DEFAULT EXALT'),
  ALK:  f('WALK TALK CHALK STALK', 'BALK', 'SIDEWALK CATWALK BOARDWALK JAYWALK MOONWALK'),
  AW:   f('CLAW DRAW LAW PAW RAW SAW JAW STRAW', 'FLAW THAW GNAW', 'JIGSAW SEESAW OUTLAW COLESLAW'),
  AWN:  f('DAWN LAWN PAWN FAWN YAWN', 'DRAWN SPAWN BRAWN PRAWN', 'WITHDRAWN OVERDRAWN'),
  AUGHT:f('CAUGHT TAUGHT BOUGHT THOUGHT', 'FOUGHT SOUGHT BROUGHT OUGHT', 'DISTRAUGHT OVERWROUGHT WROUGHT'),
  AY:   f('DAY PLAY SAY WAY STAY GRAY CLAY HAY MAY PAY', 'TRAY SPRAY SWAY PRAY AWAY DELAY THEY SLEIGH WEIGH PREY', 'BETRAY HOLIDAY ANYWAY HOORAY BIRTHDAY DISPLAY RUNWAY SUBWAY OBEY SURVEY CABARET'),
  AKE:  f('LAKE MAKE TAKE WAKE CAKE BAKE RAKE SNAKE SHAKE', 'BRAKE FLAKE STAKE QUAKE STEAK BREAK', 'MISTAKE AWAKE EARTHQUAKE MILKSHAKE CUPCAKE PANCAKE HANDSHAKE'),
  ATE:  f('DATE GATE LATE MATE HATE PLATE SKATE STATE EIGHT WAIT GREAT', 'GRATE CRATE SLATE BAIT WEIGHT STRAIGHT FREIGHT', 'CREATE DEBATE TRANSLATE RELATE'),
  ACE:  f('FACE RACE PACE PLACE SPACE LACE CASE BASE', 'GRACE BRACE TRACE CHASE VASE', 'EMBRACE ERASE STAIRCASE SUITCASE SHOWCASE PILLOWCASE'),
  AIN:  f('RAIN TRAIN BRAIN CHAIN PLAIN MAIN GAIN PAIN DRAIN LANE PLANE', 'STAIN GRAIN SPRAIN VEIN REIGN CRANE CANE', 'COMPLAIN EXPLAIN REMAIN CONTAIN TERRAIN AIRPLANE HURRICANE CHAMPAGNE'),
  AIL:  f('TAIL MAIL SAIL NAIL FAIL WHALE TALE SCALE PALE JAIL', 'SNAIL TRAIL STALE GALE FLAIL', 'DETAIL EMAIL FAIRYTALE PONYTAIL FEMALE COTTONTAIL'),
  AME:  f('NAME GAME FAME SAME CAME TAME', 'FLAME FRAME BLAME SHAME LAME AIM CLAIM', 'NICKNAME SURNAME INFLAME DISCLAIM PROCLAIM ACCLAIM'),
  AVE:  f('WAVE CAVE GAVE SAVE PAVE RAVE BRAVE', 'SLAVE SHAVE CRAVE GRAVE KNAVE', 'MICROWAVE BEHAVE ENGRAVE HEATWAVE'),
  ADE:  f('MADE SHADE BLADE GRADE FADE PAID MAID LAID AID', 'TRADE SPADE BRAID RAID WADE GLADE', 'PARADE LEMONADE AFRAID BARRICADE UPGRADE INVADE'),
  AZE:  f('MAZE DAZE GAZE HAZE RAISE PRAISE', 'BLAZE CRAZE GLAZE GRAZE PHRASE', 'AMAZE ABLAZE'),
  ABLE: f('TABLE CABLE FABLE ABLE', 'STABLE GABLE SABLE', 'UNABLE ENABLE DISABLE TURNTABLE'),
  AIR:  f('AIR FAIR HAIR PAIR CHAIR CARE SHARE BEAR PEAR WEAR THERE WHERE DARE', 'STAIR SCARE SPARE SQUARE STARE BARE FLARE GLARE SWEAR', 'DESPAIR REPAIR BEWARE UNAWARE COMPARE DECLARE MILLIONAIRE ARMCHAIR WHEELCHAIR'),
  AR:   f('STAR CAR FAR BAR JAR TAR', 'SCAR SPAR CZAR', 'GUITAR SUPERSTAR AFAR CIGAR BAZAAR SITAR'),
  ARK:  f('DARK BARK MARK PARK SHARK', 'SPARK LARK STARK', 'REMARK LANDMARK BENCHMARK TRADEMARK BOOKMARK SKYLARK WATERMARK'),
  ARM:  f('ARM FARM HARM CHARM', 'ALARM DISARM', 'FOREARM FIREARM'),
  ARD:  f('CARD HARD YARD GUARD LARD', 'SHARD BARD', 'REGARD BACKYARD POSTCARD DISCARD BOULEVARD SCORECARD'),
  ART:  f('PART CART DART HEART ART SMART START CHART TART', 'APART DEPART', 'SWEETHEART FLOWCHART UPSTART'),

  /* ---------------- E ---------------- */
  EE:   f('BEE SEE TREE FREE THREE KNEE TEA SEA KEY', 'FLEE SKI PLEA GLEE SPREE FLEA PEA', 'AGREE DEGREE REFEREE JUBILEE GUARANTEE EMPLOYEE CHIMPANZEE PEDIGREE MARQUEE DISAGREE'),
  EED:  f('SEED FEED WEED NEED SPEED BEAD', 'BREED GREED CREED TWEED FREED', 'INDEED PROCEED EXCEED SUCCEED'),
  EAK:  f('WEEK WEAK BEAK PEAK LEAK CHEEK SEEK', 'SPEAK CREEK GEEK SNEAK STREAK SQUEAK TWEAK BLEAK', 'UNIQUE ANTIQUE BOUTIQUE'),
  EEL:  f('WHEEL FEEL PEEL STEAL MEAL DEAL SEAL HEEL REAL', 'KNEEL STEEL SQUEAL PEAL REEL', 'ORDEAL REVEAL APPEAL CONCEAL'),
  EAM:  f('DREAM TEAM STEAM CREAM BEAM SEAM', 'STREAM GLEAM SCREAM THEME SCHEME', 'DAYDREAM SUPREME REDEEM ESTEEM EXTREME'),
  EEN:  f('BEAN GREEN CLEAN QUEEN SCREEN SEEN MEAN TEEN LEAN', 'SHEEN KEEN SCENE PREEN', 'MACHINE MAGAZINE SUBMARINE TANGERINE QUARANTINE'),
  EEP:  f('SLEEP DEEP KEEP JEEP CHEAP SHEEP', 'CREEP SWEEP STEEP PEEP LEAP HEAP', 'OVERSLEEP UPKEEP'),
  EET:  f('EAT HEAT MEAT SEAT BEAT NEAT FEET MEET SWEET STREET SHEET', 'TREAT WHEAT CHEAT GREET BEET TWEET SLEET', 'DEFEAT REPEAT RETREAT COMPLETE DISCREET HEARTBEAT'),
  EEZE: f('BREEZE FREEZE SNEEZE CHEESE PLEASE KNEES TREES BEES', 'SQUEEZE TEASE WHEEZE SEIZE PEAS FLEAS', 'DISEASE APPEASE'),
  EACH: f('BEACH PEACH REACH TEACH', 'SPEECH BEECH LEECH SCREECH BREACH PREACH', 'OUTREACH BESEECH OVERREACH'),
  EACE: f('PEACE PIECE LEASE CEASE', 'FLEECE GREASE', 'MASTERPIECE DECREASE INCREASE POLICE'),
  EAF:  f('LEAF CHIEF BRIEF THIEF REEF', 'GRIEF BELIEF RELIEF SHEAF', 'DISBELIEF'),
  EAVE: f('LEAVE WEAVE EVE SLEEVE', 'GRIEVE THIEVE HEAVE', 'BELIEVE RELIEVE ACHIEVE RECEIVE DECEIVE CONCEIVE PERCEIVE'),
  EAR:  f('FEAR HEAR NEAR DEAR EAR YEAR BEER DEER', 'CLEAR SPEAR CHEER PEER STEER SMEAR GEAR', 'APPEAR DISAPPEAR REINDEER ENGINEER VOLUNTEER PIONEER SINCERE CAREER SOUVENIR'),
  ED:   f('BED RED HEAD BREAD SAID DEAD SHED SLED FED', 'THREAD SPREAD INSTEAD AHEAD BEHEAD FLED SPED WED', 'OVERHEAD BEDSPREAD GINGERBREAD REDHEAD SPEARHEAD'),
  EN:   f('PEN TEN HEN MEN DEN WHEN THEN YEN', 'WREN ZEN FEN AMEN AGAIN', 'PIGPEN BULLPEN PLAYPEN'),
  ELL:  f('BELL SELL TELL WELL SHELL SMELL SPELL SWELL YELL DWELL FELL', 'CELL HELL REPEL COMPEL EXPEL EXCEL', 'FAREWELL DOORBELL SEASHELL EGGSHELL COWBELL BLUEBELL'),
  ELT:  f('BELT FELT MELT', 'PELT DWELT SMELT KNELT', 'SEATBELT'),
  ENT:  f('BENT DENT RENT TENT CENT SCENT SPENT WENT MEANT', 'LENT VENT', 'DESCENT ASCENT EXTENT INTENT CONSENT INVENT REPENT'),
  END:  f('BEND SEND LEND MEND TEND SPEND END', 'BLEND FRIEND TREND DEFEND', 'WEEKEND BOYFRIEND DEPEND PRETEND ATTEND ASCEND'),
  ENCH: f('BENCH TRENCH WRENCH', 'DRENCH STENCH CLENCH QUENCH', 'RETRENCH ENTRENCH'),
  ENSE: f('FENCE SENSE TENSE DENSE HENCE', 'PENCE WHENCE', 'DEFENSE OFFENSE INTENSE IMMENSE EXPENSE'),
  EST:  f('BEST NEST REST TEST VEST WEST PEST ZEST CHEST GUEST', 'QUEST CREST', 'REQUEST INVEST SUGGEST DETEST UNREST ARREST'),
  ET:   f('SET GET BET NET WET PET JET VET MET', 'DEBT SWEAT YET', 'FORGET REGRET UPSET CIGARETTE SILHOUETTE'),
  ESS:  f('LESS MESS DRESS PRESS CHESS GUESS', 'BLESS YES STRESS', 'SUCCESS EXCESS DISTRESS ADDRESS DEPRESS EXPRESS IMPRESS'),
  ECK:  f('NECK DECK CHECK PECK', 'SPECK WRECK HECK FLECK', 'SHIPWRECK RAINCHECK PAYCHECK'),

  /* ---------------- I ---------------- */
  IT:   f('BIT HIT SIT FIT KIT PIT SPIT SLIT KNIT', 'GRIT QUIT SPLIT TWIT', 'SUBMIT ADMIT COMMIT OMIT PERMIT'),
  IN:   f('BIN FIN PIN WIN TIN SIN GRIN SKIN THIN CHIN SPIN TWIN', 'INN DIN KIN SHIN', 'BEGIN WITHIN VIOLIN'),
  ING:  f('SING KING RING WING THING BRING SWING STING SPRING STRING', 'CLING SLING WRING FLING', 'OFFSPRING BOWSTRING HAMSTRING DRAWSTRING'),
  INK:  f('PINK SINK THINK BLINK LINK DRINK WINK RINK', 'SHRINK STINK BRINK CLINK SLINK MINK', 'RETHINK HYPERLINK CUFFLINK'),
  ICK:  f('STICK BRICK CHICK CLICK KICK LICK PICK QUICK SICK THICK TICK TRICK', 'FLICK WICK NICK SLICK', 'LIPSTICK CANDLESTICK YARDSTICK DRUMSTICK CHOPSTICK LOVESICK'),
  ILL:  f('BILL CHILL DRILL FILL GRILL HILL KILL MILL PILL SKILL SPILL STILL THRILL WILL', 'QUILL SHRILL FRILL', 'UPHILL DOWNHILL WINDMILL MOLEHILL ANTHILL'),
  IFT:  f('GIFT LIFT DRIFT SHIFT SWIFT', 'RIFT SIFT THRIFT', 'UPLIFT SNOWDRIFT SHOPLIFT'),
  IM:   f('SWIM TRIM GRIM HIM RIM DIM SKIM BRIM SLIM', 'WHIM HYMN PRIM VIM'),
  IG:   f('PIG BIG DIG FIG JIG WIG TWIG', 'GIG SPRIG', 'WHIRLIGIG THINGAMAJIG'),
  ISH:  f('FISH DISH WISH SWISH', 'SQUISH KNISH', 'GOLDFISH STARFISH JELLYFISH SHELLFISH CATFISH SWORDFISH'),
  ISS:  f('KISS MISS HISS BLISS THIS', 'ABYSS', 'DISMISS AMISS'),
  ISK:  f('DISK RISK BRISK WHISK', 'FRISK', 'ASTERISK OBELISK BASILISK'),
  IST:  f('LIST MIST FIST TWIST WRIST', 'KISSED MISSED HISSED', 'EXIST INSIST RESIST PERSIST ASSIST CONSIST'),
  ITCH: f('WITCH PITCH DITCH RICH', 'SWITCH STITCH TWITCH HITCH GLITCH', 'BEWITCH ENRICH'),
  ILT:  f('QUILT BUILT GUILT TILT', 'KILT WILT SPILT STILT HILT', 'REBUILT HOMEBUILT'),
  IMP:  f('LIMP CHIMP BLIMP SHRIMP', 'SKIMP WIMP', 'PRIMP CRIMP SCRIMP'),
  INT:  f('MINT HINT PRINT TINT LINT', 'SPRINT SQUINT FLINT GLINT STINT', 'FOOTPRINT BLUEPRINT IMPRINT PEPPERMINT PAWPRINT'),
  IP:   f('SHIP TRIP DIP HIP LIP SIP TIP ZIP CHIP FLIP SLIP DRIP GRIP WHIP SKIP', 'CLIP', 'FRIENDSHIP HARDSHIP SPACESHIP BATTLESHIP'),
  IX:   f('SIX MIX FIX', 'NIX', 'PREFIX SUFFIX AFFIX CRUCIFIX'),
  IGHT: f('LIGHT NIGHT FIGHT KITE BITE RIGHT TIGHT MIGHT SIGHT', 'BRIGHT FLIGHT KNIGHT WRITE SITE SPITE QUITE WHITE', 'DELIGHT INSIGHT MIDNIGHT TONIGHT TWILIGHT SPOTLIGHT POLITE EXCITE IGNITE UNITE INVITE DYNAMITE'),
  IDE:  f('RIDE SIDE WIDE HIDE SLIDE TIDE', 'GLIDE BRIDE PRIDE GUIDE CRIED TRIED DIED FRIED', 'DECIDE DIVIDE PROVIDE OUTSIDE INSIDE COINCIDE CONFIDE LANDSLIDE'),
  IND:  f('FIND MIND KIND BLIND HIND', 'GRIND BIND RIND', 'BEHIND REMIND MANKIND UNWIND'),
  INE:  f('LINE FINE MINE NINE PINE DINE SIGN SHINE VINE', 'SPINE TWINE WHINE DIVINE DESIGN', 'SUNSHINE PORCUPINE VALENTINE DEADLINE ENTWINE UNDERLINE'),
  IRE:  f('FIRE HIRE TIRE WIRE', 'SPIRE LIAR ADMIRE INSPIRE DESIRE ENTIRE SQUIRE', 'VAMPIRE CAMPFIRE BONFIRE EMPIRE RETIRE ACQUIRE'),
  IE:   f('SKY FLY TRY CRY DRY FRY BY MY EYE PIE TIE LIE DIE', 'SPY SHY WHY BUY HIGH THIGH SIGH', 'APPLY REPLY SUPPLY DENY ALLY RELY DEFY BUTTERFLY DRAGONFLY GOODBYE'),
  ICE:  f('ICE DICE MICE NICE RICE SLICE', 'PRICE SPICE TWICE VICE THRICE', 'ADVICE DEVICE SACRIFICE PARADISE'),
  IZE:  f('SIZE PRIZE RISE WISE EYES LIES TIES', 'SPIES FLIES CRIES', 'SURPRISE DISGUISE EXERCISE ADVISE OTHERWISE COMPRISE'),
  IVE:  f('FIVE DIVE HIVE DRIVE JIVE', 'THRIVE ALIVE', 'ARRIVE SURVIVE DEPRIVE REVIVE'),
  IPE:  f('PIPE WIPE RIPE TYPE HYPE', 'STRIPE SWIPE GRIPE', 'BAGPIPE OVERRIPE PINSTRIPE STEREOTYPE PROTOTYPE ARCHETYPE'),
  IKE:  f('BIKE HIKE LIKE STRIKE SPIKE', 'PIKE TYKE MIKE', 'ALIKE UNLIKE DISLIKE MOTORBIKE HITCHHIKE'),
  IME:  f('TIME LIME DIME CLIMB CRIME SLIME', 'RHYME PRIME CHIME GRIME MIME SUBLIME', 'OVERTIME PASTIME SOMETIME DAYTIME LIFETIME BEDTIME'),
  ILE:  f('SMILE FILE MILE PILE TILE WHILE', 'STYLE AISLE ISLE VILE', 'AWHILE MEANWHILE CROCODILE WORTHWHILE'),
  IRT:  f('SHIRT SKIRT DIRT HURT', 'FLIRT SQUIRT ALERT', 'DESSERT DIVERT INSERT EXPERT CONCERT'),
  IRL:  f('GIRL CURL PEARL SWIRL TWIRL WHIRL', 'HURL UNFURL EARL', 'SCHOOLGIRL COWGIRL UNCURL SUPERGIRL'),
  IRM:  f('WORM FIRM TERM GERM PERM', 'SQUIRM', 'CONFIRM AFFIRM'),
  URN:  f('TURN BURN LEARN EARN FERN', 'CHURN STERN YEARN SPURN', 'RETURN CONCERN SUNBURN HEARTBURN'),
  URSE: f('NURSE PURSE CURSE WORSE VERSE', 'HEARSE TERSE', 'REVERSE UNIVERSE DISPERSE REHEARSE IMMERSE'),
  URD:  f('WORD BIRD HERD NERD HEARD', 'BLURRED STIRRED PURRED SPURRED', 'ABSURD OVERHEARD MISHEARD'),

  /* ---------------- O ---------------- */
  OT:   f('HOT POT DOT LOT NOT ROT COT KNOT PLOT SLOT SPOT SHOT TROT', 'BLOT CLOT GOT WATT', 'ROBOT APRICOT MASCOT JACKPOT YACHT HOTSHOT SNAPSHOT'),
  OCK:  f('SOCK ROCK CLOCK BLOCK DOCK LOCK KNOCK SHOCK FLOCK STOCK', 'MOCK JOCK', 'PADLOCK ROADBLOCK GRIDLOCK DEADLOCK UNLOCK'),
  OP:   f('TOP HOP MOP POP DROP SHOP STOP CROP FLOP CHOP PROP', 'SLOP PLOP', 'LOLLIPOP DESKTOP LAPTOP TREETOP HILLTOP'),
  OG:   f('DOG LOG FOG FROG HOG JOG BLOG SMOG CLOG', 'SLOG GROG FLOG', 'HEDGEHOG BULLDOG CATALOG MONOLOG'),
  OB:   f('JOB ROB SOB MOB KNOB', 'BLOB SNOB SLOB COB LOB GOB', 'DOORKNOB HOBNOB CORNCOB'),
  OX:   f('BOX FOX POX OX', 'LOX SOCKS ROCKS CLOCKS BLOCKS', 'SANDBOX MAILBOX PARADOX ORTHODOX MATCHBOX JUKEBOX CHICKENPOX'),
  ONG:  f('SONG LONG STRONG WRONG GONG', 'PRONG THONG', 'ALONG BELONG LIFELONG'),
  OSS:  f('BOSS LOSS MOSS TOSS CROSS', 'FLOSS GLOSS DROSS', 'ACROSS ALBATROSS CRISSCROSS'),
  OLD:  f('BOLD COLD FOLD GOLD HOLD SOLD TOLD OLD', 'MOLD SCOLD ROLLED STROLLED', 'UNTOLD HOUSEHOLD THRESHOLD MARIGOLD UPHOLD BEHOLD'),
  OLT:  f('BOLT COLT JOLT VOLT', 'MOLT REVOLT', 'THUNDERBOLT DEADBOLT'),
  OLE:  f('HOLE ROLE POLE BOWL GOAL COAL SOUL ROLL', 'MOLE SOLE WHOLE STROLL SCROLL TOLL TROLL', 'CONTROL CONSOLE PATROL ENROLL TADPOLE LOOPHOLE'),
  OAT:  f('BOAT COAT GOAT NOTE VOTE WROTE OAT', 'FLOAT MOAT THROAT QUOTE DOTE', 'PETTICOAT SPEEDBOAT PROMOTE ANTIDOTE DENOTE OVERCOAT LIFEBOAT'),
  OAST: f('TOAST COAST GHOST POST HOST MOST ROAST', 'BOAST', 'SEACOAST GOALPOST LAMPPOST OUTPOST BEDPOST'),
  OAD:  f('ROAD LOAD TOAD CODE MODE NODE', 'ODE RODE OWED MOWED SNOWED', 'EXPLODE ERODE ABODE RAILROAD OFFLOAD DOWNLOAD UPLOAD FREELOAD'),
  OKE:  f('JOKE POKE SMOKE BROKE SPOKE WOKE OAK', 'CHOKE STROKE YOKE CLOAK SOAK', 'AWOKE BACKSTROKE ARTICHOKE INVOKE PROVOKE REVOKE'),
  OPE:  f('HOPE ROPE SOAP COPE', 'SLOPE SCOPE DOPE MOPE', 'ANTELOPE PERISCOPE MICROSCOPE TELESCOPE HOROSCOPE KALEIDOSCOPE ENVELOPE'),
  OACH: f('COACH POACH ROACH', 'BROACH', 'APPROACH ENCROACH REPROACH COCKROACH'),
  OSE:  f('NOSE ROSE HOSE POSE THOSE CHOSE', 'TOES DOZE FROZE SHOWS BLOWS GROWS FLOWS KNOWS', 'COMPOSE PROPOSE SUPPOSE EXPOSE OPPOSE DISPOSE'),
  ONE:  f('BONE CONE PHONE STONE ZONE OWN KNOWN GROWN', 'THRONE TONE DRONE ALONE BLOWN SHOWN THROWN MOAN GROAN', 'TELEPHONE MICROPHONE SAXOPHONE BACKBONE CORNERSTONE HOMEGROWN OVERTHROWN CYCLONE'),
  OWN:  f('BROWN CLOWN CROWN DOWN TOWN GOWN FROWN', 'DROWN RENOWN', 'DOWNTOWN UPTOWN HOMETOWN NIGHTGOWN BREAKDOWN COUNTDOWN SHOWDOWN'),
  OH:   f('GO NO SO SNOW BLOW KNOW GROW SHOW SLOW LOW', 'GLOW FLOW THROW CROW SEW DOUGH TOE HOE WOE FOE', 'BELOW OVERFLOW ALTHOUGH PLATEAU TABLEAU CHATEAU BUREAU'),
  OW:   f('COW HOW NOW WOW VOW BROW PLOW', 'CHOW ALLOW', 'ANYHOW SOMEHOW ENDOW DISAVOW'),
  OUT:  f('OUT SHOUT SCOUT TROUT SPOUT POUT', 'SPROUT DOUBT ABOUT', 'WITHOUT LAYOUT WORKOUT LOOKOUT BLACKOUT HANDOUT KNOCKOUT WIPEOUT'),
  OUSE: f('MOUSE HOUSE LOUSE', 'BLOUSE GROUSE SPOUSE', 'CLUBHOUSE DOGHOUSE GREENHOUSE LIGHTHOUSE WAREHOUSE BIRDHOUSE FIREHOUSE TREEHOUSE'),
  OUND: f('FOUND SOUND ROUND GROUND POUND HOUND', 'BOUND MOUND ASTOUND', 'AROUND UNDERGROUND BACKGROUND PLAYGROUND SURROUND ABOUND'),
  OUD:  f('LOUD PROUD CLOUD CROWD', 'SHROUD ALOUD ALLOWED VOWED PLOWED', 'OVERCROWD THUNDERCLOUD DISALLOWED'),
  OUR:  f('HOUR OUR SOUR FLOUR', 'TOWER POWER FLOWER SHOWER COWER SCOUR', 'SUNFLOWER CAULIFLOWER WILDFLOWER MAYFLOWER EMPOWER HORSEPOWER'),
  OWL:  f('OWL HOWL FOWL', 'TOWEL VOWEL BOWEL GROWL PROWL SCOWL JOWL', 'TROWEL DOWEL'),
  ORE:  f('MORE SHORE STORE CORE BORE FOUR DOOR FLOOR ROAR SORE WORE', 'SNORE SCORE CHORE SWORE PORE TORE POUR SOAR ORE', 'ADORE EXPLORE IGNORE BEFORE RESTORE ENCORE SEASHORE GALORE FOLKLORE SYCAMORE DINOSAUR'),
  ORN:  f('BORN CORN HORN TORN WORN THORN', 'MORN SCORN SWORN SHORN', 'ACORN POPCORN UNICORN ADORN NEWBORN FORLORN'),
  ORT:  f('SHORT SPORT COURT FORT SORT PORT', 'SNORT TORT', 'RESORT SUPPORT PASSPORT AIRPORT REPORT TRANSPORT IMPORT EXPORT'),
  ORM:  f('STORM FORM WARM NORM DORM SWARM', 'REFORM INFORM', 'PERFORM UNIFORM CONFORM TRANSFORM'),
  ORSE: f('HORSE FORCE COURSE SOURCE', 'HOARSE GORSE', 'DIVORCE REMORSE RESOURCE ENFORCE'),
  OY:   f('BOY TOY JOY SOY', 'COY ENJOY EMPLOY ANNOY DECOY', 'DESTROY CONVOY COWBOY TOMBOY CORDUROY'),
  OIL:  f('OIL BOIL COIL FOIL SOIL TOIL', 'SPOIL BROIL ROYAL LOYAL', 'UNCOIL RECOIL TINFOIL TURMOIL DISLOYAL'),
  OIN:  f('COIN JOIN LOIN', 'GROIN ADJOIN ENJOIN', 'SIRLOIN PURLOIN'),
  OOM:  f('ROOM BROOM BLOOM BOOM ZOOM DOOM', 'GLOOM GROOM LOOM TOMB WOMB PLUME FUME', 'MUSHROOM BEDROOM CLASSROOM BALLROOM HEIRLOOM ASSUME CONSUME PERFUME COSTUME'),
  OON:  f('MOON SOON SPOON NOON TUNE JUNE DUNE', 'PRUNE LOON SWOON BALLOON CARTOON', 'RACCOON LAGOON MAROON MONSOON HARPOON TYPHOON COCOON BASSOON BUFFOON'),
  OOL:  f('COOL FOOL POOL SCHOOL TOOL STOOL', 'SPOOL RULE DROOL', 'CARPOOL WHIRLPOOL OVERRULE PRESCHOOL HOMESCHOOL'),
  OOT:  f('BOOT ROOT SHOOT FRUIT SUIT CUTE HOOT', 'LOOT FLUTE MUTE BRUTE ROUTE SCOOT', 'SALUTE DISPUTE COMPUTE TRIBUTE PURSUIT PARACHUTE RECRUIT'),
  OOF:  f('ROOF HOOF PROOF', 'SPOOF ALOOF', 'WATERPROOF FIREPROOF BULLETPROOF SOUNDPROOF'),
  OO:   f('BLUE GLUE TRUE CLUE TWO ZOO SHOE YOU NEW', 'CREW CHEW GREW FLEW KNEW DUE HUE SCREW THREW STEW', 'KANGAROO SHAMPOO TATTOO BAMBOO CANOE KAZOO CUCKOO IGLOO'),
  OOK:  f('BOOK COOK HOOK LOOK TOOK SHOOK', 'CROOK BROOK NOOK', 'NOTEBOOK COOKBOOK OVERLOOK UNDERTOOK OUTLOOK TEXTBOOK'),
  OOD:  f('FOOD MOOD RUDE DUDE', 'BROOD PRUDE SHREWD CRUDE', 'ATTITUDE GRATITUDE ALTITUDE INTRUDE EXCLUDE INCLUDE CONCLUDE'),
  OUP:  f('SOUP LOOP HOOP GROUP TROOP', 'SCOOP SWOOP STOOP DROOP COUP SNOOP WHOOP', 'HULAHOOP NINCOMPOOP'),
  UCE:  f('JUICE GOOSE MOOSE LOOSE', 'SPRUCE TRUCE NOOSE DEUCE', 'REDUCE INDUCE SEDUCE PRODUCE INTRODUCE CABOOSE'),

  /* ---------------- U ---------------- */
  UD:   f('MUD BUD BLOOD FLOOD', 'STUD THUD SPUD DUD CUD'),
  UG:   f('BUG HUG JUG MUG RUG TUG PLUG DRUG', 'SHRUG SNUG SLUG THUG DUG', 'LADYBUG HUMBUG FIREBUG JITTERBUG EARPLUG'),
  UB:   f('CUB PUB RUB TUB CLUB', 'SCRUB SHRUB GRUB STUB HUB SUB', 'BATHTUB NIGHTCLUB HOTTUB'),
  UN:   f('SUN FUN RUN BUN GUN ONE SON DONE WON', 'NUN TON STUN SPUN SHUN PUN', 'BEGUN UNDONE OUTRUN SHOTGUN HANDGUN OVERDONE'),
  UM:   f('GUM HUM DRUM PLUM SUM MUM SOME COME', 'THUMB CRUMB DUMB NUMB STRUM SCUM', 'OVERCOME BECOME BUBBLEGUM HUMDRUM'),
  UMP:  f('BUMP DUMP JUMP LUMP PUMP', 'STUMP CLUMP PLUMP THUMP SLUMP HUMP TRUMP', 'GRUMP CHUMP FRUMP'),
  UNK:  f('JUNK PUNK TRUNK BUNK SUNK', 'SKUNK CHUNK DRUNK FLUNK SPUNK', 'SHRUNK PLUNK CLUNK HUNK MONK'),
  UCK:  f('DUCK LUCK TRUCK STUCK BUCK TUCK SUCK', 'MUCK CLUCK PLUCK CHUCK YUCK', 'AMUCK POTLUCK SCHMUCK FIRETRUCK'),
  UST:  f('BUST DUST RUST TRUST JUST MUST', 'GUST CRUST THRUST', 'ADJUST ROBUST SAWDUST STARDUST MISTRUST DISGUST UNJUST'),
  UNCH: f('LUNCH BUNCH PUNCH CRUNCH MUNCH', 'HUNCH BRUNCH SCRUNCH'),
  UT:   f('CUT HUT NUT BUT GUT SHUT', 'JUT RUT STRUT SMUT', 'COCONUT PEANUT WALNUT DOUGHNUT CHESTNUT HAZELNUT UNDERCUT SHORTCUT'),
  UFF:  f('PUFF STUFF ROUGH TOUGH', 'ENOUGH FLUFF BLUFF CUFF HUFF SCUFF SNUFF', 'HANDCUFF REBUFF GRUFF POWDERPUFF'),
  UDGE: f('JUDGE FUDGE BUDGE NUDGE', 'SMUDGE GRUDGE TRUDGE SLUDGE', 'DRUDGE ADJUDGE PREJUDGE MISJUDGE'),
  UP:   f('CUP PUP UP', 'SUP', 'BUTTERCUP HICCUP TEACUP EGGCUP'),
  UMBLE:f('TUMBLE JUMBLE HUMBLE RUMBLE', 'MUMBLE GRUMBLE STUMBLE CRUMBLE FUMBLE BUMBLE'),
  ATTER:f('BATTER MATTER CHATTER PATTER', 'SCATTER SHATTER FLATTER LATTER CLATTER', 'SPLATTER TATTER NATTER PITTERPATTER'),
  UTTER:f('BUTTER GUTTER UTTER MUTTER CUTTER', 'SHUTTER STUTTER CLUTTER FLUTTER SPUTTER', 'SPLUTTER'),
  ITTER:f('LITTER BITTER SITTER FITTER', 'GLITTER TWITTER JITTER SKITTER CRITTER', 'BABYSITTER')
};

/* --------------------------------------------------------------------------
   Legacy category words kept so nothing that imports WORD_FAMILIES.core /
   .longWords breaks. These are NOT rhyme families.
   -------------------------------------------------------------------------- */
const LEGACY_CORE = ["CAT","NIGHT","CAKE","RING","BOAT","BEAR","TRAIN","CLOCK","STAR","CHAIR","BLUE","BONE","SAND","DOG","TREE","SUN","MOON","FISH","DUCK","PEN","CUP","BED","PIG","FOX","HOUSE","CAR","DOOR","BOOK","GAME","BALL","FIRE","GOLD","ICE","SNOW","WIND","CLOUD","RAIN","STORM","WAVE","HILL","ROCK","ROAD","PATH","BRIDGE","TOWN","STREET","PARK","SHOP","FARM","BARN","BIRD","COW","HORSE","SHEEP","GOAT","DEER","WOLF","SNAKE","FROG","CRAB","WHALE","SHARK","SEAL","BEE","ANT","FLY","WORM","SPIDER","EYE","NOSE","EAR","MOUTH","HAND","FOOT","LEG","ARM","HEART","MIND","TIME","DAY","WEEK","MONTH","YEAR","SPRING","SUMMER","FALL","WINTER","MORNING","NOON","EVENING","DAWN","DUSK","RED","GREEN","YELLOW","BLACK","WHITE","GRAY"];
const LEGACY_LONG = ["ABDOMEN","ASTRONAUT","BICYCLE","BUTTERFLY","CALENDAR","CHOCOLATE","DIAMOND","ELEPHANT","FESTIVAL","GALAXY","HARMONY","HORIZON","INSTRUMENT","JUNGLE","KANGAROO","LAVENDER","MICROSCOPE","NECTAR","OXYGEN","PENGUIN","QUARTER","RADIATOR","SYMPHONY","TELESCOPE","UMBRELLA","VOLCANO","WATERFALL","XYLOPHONE","YOGURT","ZEPPELIN","ACADEMY","BACTERIA","CABINET","DAFFODIL","ECONOMY","FACTORY","GEOMETRY","HELICOPTER","ILLUSION","JOURNAL","KEYBOARD","LABORATORY","MACHINERY","NOVELIST","ORCHESTRA","PARACHUTE","QUADRANT","REPTILE","SATELLITE","THERMOMETER","UNIVERSE","VACUUM","WILDERNESS","YACHT","ZOOLOGY","ALGEBRA","BROCCOLI","CAPITAL","DINOSAUR","ELEVATOR","FURNITURE","GOVERNOR","HOSPITAL","INVENTOR","JUSTICE","KINETIC","LIBRARY","MONUMENT","NARRATIVE","OASIS","PYRAMID","QUESTION","RESTAURANT","STADIUM","TRIANGLE","UTENSIL","VEHICLE","WEATHER","YIELD","ZEBRA","ARCHITECT","BALCONY","CAMERA","DOCUMENT","ENVELOPE","FEATHER","GALLERY","HERITAGE","ISLAND","JACKET","KITCHEN","LUGGAGE","MEDICINE","NETWORK","OFFICER","PASSENGER","QUALITY","RECIPE","SCIENTIST","TEACHER"];

/* --------------------------------------------------------------------------
   Derived, backwards-compatible structures
   -------------------------------------------------------------------------- */
const RHYME_FAMILY_KEYS = Object.keys(FAMILY_TIERS);

// Flat arrays per family (same shape the game already used).
const WORD_FAMILIES = { core: LEGACY_CORE, longWords: LEGACY_LONG };
RHYME_FAMILY_KEYS.forEach(k => {
  const t = FAMILY_TIERS[k];
  WORD_FAMILIES[k] = [...t.easy, ...t.medium, ...t.hard];
});

const WORD_BANK = Array.from(new Set(Object.values(WORD_FAMILIES).flat()));

// word -> tier
const TIER_OF = new Map();
RHYME_FAMILY_KEYS.forEach(k => {
  ['easy', 'medium', 'hard'].forEach(tier => FAMILY_TIERS[k][tier].forEach(w => TIER_OF.set(w, tier)));
});

// Target pools by difficulty level.
const TARGET_POOLS = {
  easy:   Array.from(TIER_OF).filter(([, t]) => t === 'easy').map(([w]) => w),
  normal: Array.from(TIER_OF).filter(([, t]) => t !== 'hard').map(([w]) => w),
  hard:   Array.from(TIER_OF).filter(([, t]) => t !== 'easy').map(([w]) => w)
};
const QUALITY_WORDS = TARGET_POOLS.normal;

const RECENT_TARGET_LIMIT = 18;
const RECENT_FAMILY_LIMIT = 8; // bigger bank -> can afford a longer family cooldown

const wordToFamilies = new Map();
RHYME_FAMILY_KEYS.forEach(family => {
  WORD_FAMILIES[family].forEach(word => {
    if (!wordToFamilies.has(word)) wordToFamilies.set(word, []);
    wordToFamilies.get(word).push(family);
  });
});

function familyOf(word){
  const upper = word.toUpperCase();
  const families = wordToFamilies.get(upper);
  return families ? families[0] : 'other:' + upper.slice(-3);
}

/* Known rhymes for a target (useful for host hints / judging aid).
   Returns words ordered easy -> hard, excluding the target itself. */
function getRhymes(target, { tier = null, limit = 0 } = {}){
  const fam = familyOf(target);
  const t = FAMILY_TIERS[fam];
  if (!t) return [];
  const order = tier ? [tier] : ['easy', 'medium', 'hard'];
  const out = order.flatMap(x => t[x]).filter(w => w !== target.toUpperCase());
  return limit ? out.slice(0, limit) : out;
}
/* true = known rhyme, false = not in bank (NOT proof it doesn't rhyme; host still judges). */
function isKnownRhyme(target, guess){
  const g = guess.toUpperCase(), t = target.toUpperCase();
  if (g === t) return false;
  const fam = familyOf(t);
  return (wordToFamilies.get(g) || []).includes(fam);
}

function loadTargetHistory(){
  try {
    const data = JSON.parse(localStorage.getItem('rhymeMatchTargets') || '{}');
    return {
      words: Array.isArray(data.words) ? data.words.slice(-RECENT_TARGET_LIMIT) : [],
      families: Array.isArray(data.families) ? data.families.slice(-RECENT_FAMILY_LIMIT) : []
    };
  } catch(e){ return { words:[], families:[] }; }
}
let targetHistory = loadTargetHistory();
function rememberTarget(word){
  const upper = word.toUpperCase();
  targetHistory.words = [...targetHistory.words.filter(w => w !== upper), upper].slice(-RECENT_TARGET_LIMIT);
  targetHistory.families = [...targetHistory.families, familyOf(upper)].slice(-RECENT_FAMILY_LIMIT);
  try { localStorage.setItem('rhymeMatchTargets', JSON.stringify(targetHistory)); } catch(e){}
}

/* Picks a random target.
   level: 'easy' (everyday 1-syllable words), 'normal' (default: easy + medium),
          'hard' (medium + hard).
   Picks the FAMILY first (so big families like AY don't dominate), then a word
   inside it, so every rhyme sound gets fair airtime. */
function pickTarget(level = 'normal'){
  const pool = TARGET_POOLS[level] || TARGET_POOLS.normal;
  const byFamily = new Map();
  pool.forEach(w => {
    if (targetHistory.words.includes(w)) return;
    const fam = familyOf(w);
    if (!byFamily.has(fam)) byFamily.set(fam, []);
    byFamily.get(fam).push(w);
  });
  let fams = Array.from(byFamily.keys()).filter(fam => !targetHistory.families.includes(fam));
  if (!fams.length) fams = Array.from(byFamily.keys());
  if (!fams.length) return pool[Math.floor(Math.random() * pool.length)];
  const fam = fams[Math.floor(Math.random() * fams.length)];
  const words = byFamily.get(fam);
  return words[Math.floor(Math.random() * words.length)];
}

/* ==========================================================================
   TWIST CHALLENGES (unchanged behaviour; now fed by the bigger bank)
   Twists are only selected when at least two known rhymes satisfy them.
   ========================================================================== */
function syllables(word){
  let w = word.toLowerCase().replace(/qu/g, 'q').replace(/^y/, '');
  if (w.length <= 3) return 1;
  if (!/[^aeiouy]le$/.test(w)) w = w.replace(/(?:[^aeiouy]es|ed|e)$/, '');
  const m = w.match(/[aeiouy]{1,2}/g);
  return m ? m.length : 1;
}
const TWIST_TAGS = {
  food:'CAKE CUPCAKE PANCAKE MILKSHAKE STEAK RICE SPICE SLICE MEAT WHEAT TREAT POT TEAPOT CARROT APRICOT CORN POPCORN ACORN GHEE PUREE COFFEE TOFFEE MUSHROOM PLUM GUM SOUP JUICE CHEESE BREAD FRUIT PEACH PEA BEAN BEET SHRIMP LUNCH BRUNCH FUDGE PEANUT WALNUT COCONUT DOUGHNUT CHESTNUT HAZELNUT TANGERINE ARTICHOKE LEMONADE MARZIPAN GINGERBREAD SUCCOTASH TOAST BUTTER SALT',
  animal:'BAT RAT GNAT WOMBAT MUSKRAT DRAKE SNAKE RATTLESNAKE MOUSE GROUSE MOLE TADPOLE DEER REINDEER TROUT OWL HAWK LARK SHARK SKUNK CHICK COW CROW CRAB PIG DOG FROG HOG GOAT WHALE SHEEP HEN BEAR PELICAN CHIMP SHRIMP MONK KANGAROO DINOSAUR HEDGEHOG BULLDOG RACCOON PORCUPINE GOLDFISH STARFISH JELLYFISH CATFISH SWORDFISH BUTTERFLY DRAGONFLY LADYBUG COCKROACH MOOSE GOOSE FLEA MICE',
  object:'HAT MAT DOORMAT TRAY CLAY RAKE BRAKE STAKE LAMP FRAME BROOM ROOM PHONE STONE BRICK STICK CLOCK SOCK BLOCK BAG FLAG MUG RUG JUG CUP PEN KEY BELL DRUM KNOB TOOL SPOON BOOK BOOT SUIT TUB BIN PIN PAD LOCK PADLOCK NOTEBOOK COOKBOOK LAPTOP DESKTOP CANDLESTICK DRUMSTICK CHOPSTICK HANDBAG SANDBAG SUITCASE BAGPIPE MICROSCOPE TELESCOPE',
  place:'LAKE SHORE STORE PARK LANDMARK ROOM BEDROOM CLASSROOM BALLROOM DOWNTOWN UPTOWN HOMETOWN SEASHORE OFFSHORE AIRPORT PORT COURT FORT TOWN HOUSE CLUBHOUSE DOGHOUSE GREENHOUSE LIGHTHOUSE WAREHOUSE BIRDHOUSE TREEHOUSE FIREHOUSE SCHOOL POOL YARD BACKYARD PLAYGROUND SUBWAY HIGHWAY LANE ISLE COAST SEACOAST',
  job:'KING GROOM REFEREE ENGINEER VOLUNTEER PIONEER OFFICER SCIENTIST TEACHER INVENTOR GOVERNOR NURSE SCOUT JUDGE COACH ACROBAT DIPLOMAT COWBOY BABYSITTER CHIEF HOST BOSS NERD',
  nature:'SUNLIGHT MOONLIGHT STARLIGHT DAYLIGHT LAKE FLAME RAIN CLOUD STORM WAVE WIND STAR ROCK TREE SNOW HILL BREEZE THORN DAWN SKY SEA MOON SUN LEAF FLOWER SUNFLOWER WILDFLOWER MAYFLOWER SAND SHORE CAVE GRASS STONE DUNE MOSS FERN WEATHER HEATWAVE SUNSHINE',
  sound:'BELL COWBELL DOORBELL YELL HOWL GROWL SQUEAK CREAK BANG CLANG SONG GONG HUM DRUM BOOM ZING SHOUT SNORE THUD THUMP SPLASH CRASH CLICK BUZZ QUACK CLUCK SNEEZE WHEEZE ROAR MEOW TWEET HOOT SIGH LOUD ALOUD',
  clothing:'HAT COAT GOWN NIGHTGOWN SHIRT SKIRT VEST JACKET SHOES SOCK BOOT SUIT CLOAK OVERCOAT PETTICOAT CORDUROY SLEEVE',
  travel:'TRAIN PLANE BOAT ROAD RUNWAY HIGHWAY SUBWAY GATEWAY PASSPORT AIRPORT PORT CAR CAB VAN SHIP SPACESHIP BATTLESHIP SPEEDBOAT LIFEBOAT AIRPLANE TAXICAB CARAVAN BIKE MOTORBIKE YACHT TRUCK RIDE JEEP',
  celebration:'CAKE CUPCAKE BIRTHDAY HOLIDAY HOORAY JUBILEE JAMBOREE PARTY PRESENT GIFT CROWN DANCE PARADE BALLOON CARTOON LEMONADE CHAMPAGNE',
  tiny:'ANT GNAT BUG MICE COIN SEED DICE PEA DOT CRUMB SPECK GRAIN FLEA BIT',
  spooky:'FRIGHT NIGHT MIDNIGHT GLOOM DOOM GHOST VAMPIRE CURSE DARK SHADOW WITCH BEWITCH BAT SKELETON TOMB DEADLOCK',
  action:'PLAY STAY PRAY SING BRING SWING FLY TRY JUMP BUMP CLAP SNAP RAP TAP DRAW SAW WALK TALK TURN BURN SHOUT SWIM SKIP HIKE RIDE SLIDE CATCH THROW KICK RUN DANCE CLIMB HOP SPIN TWIRL DIVE',
  feeling:'JOY GLEE DELIGHT FRIGHT SHAME BLAME DESPAIR HOPE LOVE FEAR SCARE GLAD SAD MAD PRIDE GRIEF BLISS CALM',
  funny:'JOKE CLOWN PRANK GAG WIG GOOF ZING SPLAT BRAT SILLY GIGGLE WACKY',
  party:'CAKE CUPCAKE PANCAKE MILKSHAKE GAME HAT CROWN GIFT PRESENT JOKE BALLOON LEMONADE DANCE SONG'
};
const TWIST_TAG_LABELS = {
  food:'something edible', animal:'an animal', object:'an object you could use', place:'a place', job:'a job or role', nature:'something from nature', sound:'a sound or something noisy', clothing:'something you could wear', travel:'something linked to travel', celebration:'something at a celebration', tiny:'something tiny', spooky:'something spooky', action:'an action', feeling:'a feeling', funny:'something funny', party:'something you could bring to a party'
};
const TWIST_CHALLENGES = [
  ...Array.from({length:8},(_,i) => ({id:`length-${i+3}`, text:`Use exactly ${i+3} letters.`, test:w => w.length === i+3})),
  {id:'short',text:'Use a short rhyme: 3–5 letters.',test:w => w.length >= 3 && w.length <= 5},
  {id:'long',text:'Use a long rhyme: at least 8 letters.',test:w => w.length >= 8},
  {id:'one-syllable',text:'Use a one-syllable rhyme.',test:w => syllables(w) === 1},
  {id:'two-syllable',text:'Use a two-syllable rhyme.',test:w => syllables(w) === 2},
  {id:'three-plus-syllable',text:'Use a rhyme with 3 or more syllables.',test:w => syllables(w) >= 3},
  {id:'verb',text:'Use a verb: something a person can do.',test:w => TWIST_TAGS.action.split(' ').includes(w)},
  {id:'ends-in-s',text:'Use a word ending in S.',test:w => w.endsWith('S') && !w.endsWith('SS')},
  {id:'compound',text:'Use a compound word.',test:w => w.length >= 8 && /(DAY|LIGHT|HOUSE|ROOM|WAY|TIME|LAND|WORD|WORK|BOAT|COAT|BALL|BOOK|FISH|FLOWER|WALK|SHIP|BOX|TOWN|YARD|LOCK|STICK|PROOF)/.test(w)},
  {id:'different-spelling',text:'Use a rhyme that is spelled differently at the end.',test:(w) => true, needsTarget:true},
  ...'AEIOU'.split('').map(letter => ({id:`contains-${letter}`,text:`Use a rhyme containing the letter ${letter}.`,test:w => w.includes(letter)})),
  ...'BCDFGHJKLMNPRSTW'.split('').map(letter => ({id:`starts-${letter}`,text:`Use a rhyme beginning with ${letter}.`,test:w => w.startsWith(letter)})),
  ...Object.entries(TWIST_TAGS).map(([id,words]) => ({id:`category-${id}`,text:`Use ${TWIST_TAG_LABELS[id]}.`,test:w => words.split(' ').includes(w)}))
];
function pickTwistChallenge(target, history){
  const words = getRhymes(target);
  // 'different-spelling' needs the target, so it is evaluated here
  const tail = target.slice(-2);
  const dynamic = TWIST_CHALLENGES.map(c => c.needsTarget
    ? { ...c, test: w => w.slice(-2) !== tail }
    : c);
  let eligible = dynamic.filter(challenge => words.filter(challenge.test).length >= 2);
  if (!eligible.length) return { id:'different-first-letter', text:`Use a rhyme that starts with a different letter than ${target}.` };
  const fresh = eligible.filter(challenge => !history.includes(challenge.id));
  if (fresh.length) eligible = fresh;
  const chosen = eligible[Math.floor(Math.random() * eligible.length)];
  return { id:chosen.id, text:chosen.text };
}

export {
  WORD_FAMILIES, WORD_BANK, QUALITY_WORDS,
  FAMILY_TIERS, TIER_OF, TARGET_POOLS,
  familyOf, getRhymes, isKnownRhyme,
  rememberTarget, pickTarget, pickTwistChallenge
};
