/* Curated US-English rhyme families. The bank is a hint for target/twist selection;
   the human host remains authoritative when judging submitted words. */
import { normalizeWord } from './normalize.js';
const f = (easy, medium = '', hard = '') => ({
  easy: easy.split(' ').filter(Boolean),
  medium: medium.split(' ').filter(Boolean),
  hard: hard.split(' ').filter(Boolean)
});

const FAMILY_TIERS = {
  AT: f('BAT HAT MAT RAT CAT FAT PAT SAT FLAT CHAT THAT', 'SPLAT BRAT GNAT TOMCAT VAT', 'DOORMAT MUSKRAT COPYCAT WOMBAT'),
  AN: f('CAN FAN MAN PAN RAN VAN TAN PLAN SCAN CLAN BAN', 'SPAN BEGAN OUTRAN SUNTAN', 'CARAVAN SUPERMAN'),
  AP: f('CAP MAP TAP NAP GAP LAP CLAP SNAP TRAP WRAP', 'FLAP SLAP STRAP ZAP CHAP SCRAP', 'MISHAP MOUSETRAP HANDICAP KIDNAP'),
  AG: f('BAG TAG FLAG WAG NAG RAG DRAG', 'SNAG STAG BRAG SAG SHAG', 'HANDBAG SANDBAG'),
  AB: f('CRAB GRAB LAB TAB CAB', 'SLAB JAB DAB NAB SCAB FLAB BLAB DRAB', 'TAXICAB'),
  AD: f('BAD DAD MAD SAD GLAD PAD HAD', 'CLAD FAD LAD PLAID', 'NOTEPAD'),
  AM: f('HAM JAM RAM DAM CLAM SLAM SCAM', 'SPAM TRAM DRAM SHAM SWAM', 'DIAGRAM TELEGRAM ANAGRAM PROGRAM'),
  ACK: f('BACK PACK SACK TACK RACK BLACK SNACK TRACK CRACK QUACK', 'SHACK STACK SMACK WHACK JACK LACK', 'BACKPACK HAYSTACK PAPERBACK FLAPJACK'),
  ASH: f('CASH DASH MASH RASH SASH BASH', 'FLASH CRASH SPLASH TRASH SMASH SLASH CLASH STASH', 'EYELASH BACKLASH'),
  ASS: f('PASS CLASS GLASS GRASS BRASS MASS', 'SASS LASS ALAS', 'BYPASS SURPASS UNDERPASS HOURGLASS'),
  ATCH: f('CATCH MATCH BATCH LATCH PATCH HATCH', 'SCRATCH SNATCH THATCH', 'DISPATCH MISMATCH'),
  ANK: f('BANK TANK RANK SANK THANK', 'BLANK PLANK FRANK PRANK DRANK SPANK CRANK YANK', 'SHRANK'),
  AND: f('BAND HAND LAND SAND STAND GRAND BRAND', 'STRAND EXPAND COMMAND DEMAND', 'UNDERSTAND WONDERLAND HEADBAND QUICKSAND SECONDHAND'),
  ANG: f('BANG GANG HANG RANG SANG SLANG FANG', 'CLANG PANG', 'BOOMERANG MUSTANG'),
  ANCE: f('DANCE CHANCE GLANCE', 'TRANCE PRANCE STANCE', 'ADVANCE ENHANCE PERCHANCE ROMANCE'),
  ANT: f('PANT CHANT GRANT PLANT SLANT RANT', 'SCANT ENCHANT', 'SUPPLANT TRANSPLANT RECANT'),
  ALL: f('BALL CALL FALL HALL MALL TALL WALL SMALL STALL', 'APPALL INSTALL', 'WATERFALL BASKETBALL OVERALL SNOWBALL'),
  ALT: f('SALT MALT HALT', 'FAULT VAULT', 'ASSAULT SOMERSAULT DEFAULT EXALT'),
  ALK: f('WALK TALK CHALK STALK', 'BALK', 'SIDEWALK CATWALK BOARDWALK JAYWALK'),
  AW: f('CLAW DRAW LAW PAW SAW JAW STRAW', 'FLAW THAW GNAW', 'JIGSAW SEESAW OUTLAW'),
  AWN: f('DAWN LAWN PAWN FAWN YAWN', 'DRAWN SPAWN BRAWN PRAWN', 'WITHDRAWN OVERDRAWN'),
  AUGHT: f('CAUGHT TAUGHT BOUGHT THOUGHT', 'FOUGHT SOUGHT BROUGHT OUGHT', 'DISTRAUGHT OVERWROUGHT WROUGHT'),
  AY: f('DAY PLAY SAY WAY STAY GRAY CLAY HAY MAY PAY', 'TRAY SPRAY SWAY PRAY AWAY DELAY THEY SLEIGH WEIGH PREY', 'BETRAY HOLIDAY ANYWAY HOORAY BIRTHDAY DISPLAY RUNWAY SUBWAY OBEY SURVEY CABARET'),
  AKE: f('LAKE MAKE TAKE WAKE CAKE BAKE RAKE SNAKE SHAKE', 'BRAKE FLAKE STAKE QUAKE STEAK BREAK', 'MISTAKE AWAKE EARTHQUAKE MILKSHAKE CUPCAKE PANCAKE HANDSHAKE'),
  ATE: f('DATE GATE LATE MATE HATE PLATE SKATE STATE EIGHT WAIT GREAT', 'GRATE CRATE SLATE BAIT WEIGHT STRAIGHT FREIGHT', 'CREATE DEBATE TRANSLATE RELATE'),
  ACE: f('FACE RACE PACE PLACE SPACE LACE CASE BASE', 'GRACE BRACE TRACE CHASE', 'EMBRACE ERASE STAIRCASE SUITCASE SHOWCASE'),
  AIN: f('RAIN TRAIN BRAIN CHAIN PLAIN MAIN GAIN PAIN DRAIN LANE PLANE', 'STAIN GRAIN SPRAIN VEIN REIGN CRANE CANE', 'COMPLAIN EXPLAIN REMAIN CONTAIN TERRAIN AIRPLANE HURRICANE'),
  AIL: f('TAIL MAIL SAIL NAIL FAIL WHALE TALE SCALE PALE JAIL', 'SNAIL TRAIL STALE GALE FLAIL', 'DETAIL EMAIL FAIRYTALE PONYTAIL FEMALE'),
  AME: f('NAME GAME FAME SAME CAME TAME', 'FLAME FRAME BLAME SHAME LAME AIM CLAIM', 'NICKNAME SURNAME INFLAME DISCLAIM PROCLAIM ACCLAIM'),
  AVE: f('WAVE CAVE GAVE SAVE PAVE RAVE BRAVE', 'SHAVE CRAVE GRAVE KNAVE', 'MICROWAVE BEHAVE ENGRAVE'),
  ADE: f('MADE SHADE BLADE GRADE FADE PAID MAID LAID AID', 'TRADE SPADE BRAID RAID WADE GLADE', 'PARADE LEMONADE AFRAID BARRICADE UPGRADE INVADE'),
  AZE: f('MAZE DAZE GAZE HAZE RAISE PRAISE', 'BLAZE CRAZE GLAZE GRAZE PHRASE', 'AMAZE ABLAZE'),
  ABLE: f('TABLE CABLE FABLE ABLE', 'STABLE GABLE SABLE', 'UNABLE ENABLE DISABLE TURNTABLE'),
  AIR: f('AIR FAIR HAIR PAIR CHAIR CARE SHARE BEAR PEAR WEAR THERE WHERE DARE', 'STAIR SCARE SPARE SQUARE STARE BARE FLARE GLARE SWEAR', 'DESPAIR REPAIR BEWARE UNAWARE COMPARE DECLARE MILLIONAIRE ARMCHAIR WHEELCHAIR'),
  AR: f('STAR CAR FAR BAR JAR TAR', 'SCAR SPAR CZAR', 'GUITAR SUPERSTAR AFAR CIGAR BAZAAR SITAR'),
  ARK: f('DARK BARK MARK PARK SHARK', 'SPARK LARK STARK', 'REMARK LANDMARK BENCHMARK TRADEMARK SKYLARK WATERMARK'),
  ARM: f('ARM FARM HARM CHARM', 'ALARM DISARM', 'FOREARM FIREARM'),
  ARD: f('CARD HARD YARD GUARD LARD', 'SHARD BARD', 'REGARD BACKYARD POSTCARD DISCARD BOULEVARD SCORECARD'),
  ART: f('PART CART DART HEART ART SMART START CHART TART', 'APART DEPART', 'SWEETHEART FLOWCHART UPSTART'),
  EE: f('BEE SEE TREE FREE THREE KNEE TEA SEA KEY', 'FLEE SKI PLEA GLEE SPREE FLEA PEA', 'AGREE DEGREE REFEREE JUBILEE GUARANTEE MARQUEE DISAGREE'),
  EED: f('SEED FEED WEED NEED SPEED BEAD', 'BREED GREED CREED TWEED FREED', 'INDEED PROCEED EXCEED SUCCEED'),
  EAK: f('WEEK WEAK BEAK PEAK LEAK CHEEK SEEK', 'SPEAK CREEK GEEK SNEAK STREAK SQUEAK TWEAK BLEAK', 'UNIQUE ANTIQUE BOUTIQUE'),
  EEL: f('WHEEL FEEL PEEL STEAL MEAL DEAL SEAL HEEL REAL', 'KNEEL STEEL SQUEAL PEAL REEL', 'ORDEAL REVEAL APPEAL CONCEAL'),
  EAM: f('DREAM TEAM STEAM CREAM BEAM SEAM', 'STREAM GLEAM SCREAM THEME SCHEME', 'DAYDREAM SUPREME REDEEM ESTEEM EXTREME'),
  EEN: f('BEAN GREEN CLEAN QUEEN SCREEN SEEN MEAN TEEN LEAN', 'SHEEN KEEN SCENE PREEN', 'MACHINE MAGAZINE SUBMARINE TANGERINE QUARANTINE'),
  EEP: f('SLEEP DEEP KEEP JEEP CHEAP SHEEP', 'CREEP SWEEP STEEP PEEP LEAP HEAP', 'OVERSLEEP UPKEEP'),
  EET: f('EAT HEAT MEAT SEAT BEAT NEAT FEET MEET SWEET STREET SHEET', 'TREAT WHEAT CHEAT GREET BEET TWEET SLEET', 'DEFEAT REPEAT RETREAT COMPLETE DISCREET HEARTBEAT'),
  EEZE: f('BREEZE FREEZE SNEEZE CHEESE PLEASE KNEES TREES BEES', 'SQUEEZE TEASE WHEEZE SEIZE PEAS FLEAS', 'DISEASE APPEASE'),
  EACH: f('BEACH PEACH REACH TEACH', 'SPEECH BEECH LEECH SCREECH BREACH PREACH', 'OUTREACH BESEECH OVERREACH'),
  EACE: f('PEACE PIECE LEASE CEASE', 'FLEECE GREASE', 'MASTERPIECE DECREASE INCREASE POLICE'),
  EAF: f('LEAF CHIEF BRIEF THIEF REEF', 'GRIEF BELIEF RELIEF SHEAF', 'DISBELIEF'),
  EAVE: f('LEAVE WEAVE EVE SLEEVE', 'GRIEVE THIEVE HEAVE', 'BELIEVE RELIEVE ACHIEVE RECEIVE DECEIVE CONCEIVE PERCEIVE'),
  EAR: f('FEAR NEAR DEAR EAR YEAR BEER DEER', 'CLEAR SPEAR CHEER PEER STEER SMEAR GEAR', 'APPEAR DISAPPEAR REINDEER ENGINEER VOLUNTEER PIONEER SINCERE CAREER SOUVENIR'),
  ED: f('BED RED HEAD BREAD SAID DEAD SHED SLED FED', 'THREAD SPREAD INSTEAD AHEAD BEHEAD FLED SPED WED', 'OVERHEAD BEDSPREAD GINGERBREAD REDHEAD SPEARHEAD'),
  EN: f('PEN TEN HEN MEN DEN WHEN THEN YEN', 'WREN ZEN FEN AMEN AGAIN', 'BULLPEN PLAYPEN'),
  ELL: f('BELL SELL TELL WELL SHELL SMELL SPELL SWELL YELL DWELL FELL', 'CELL HELL REPEL COMPEL EXPEL EXCEL', 'FAREWELL DOORBELL SEASHELL EGGSHELL COWBELL BLUEBELL'),
  ELT: f('BELT FELT MELT', 'PELT DWELT SMELT KNELT', 'SEATBELT'),
  ENT: f('BENT DENT RENT TENT CENT SCENT SPENT WENT MEANT', 'LENT VENT', 'DESCENT ASCENT EXTENT INTENT CONSENT INVENT REPENT'),
  END: f('BEND SEND LEND MEND TEND SPEND END', 'BLEND FRIEND TREND DEFEND', 'WEEKEND BOYFRIEND DEPEND PRETEND ATTEND ASCEND'),
  ENCH: f('BENCH TRENCH WRENCH', 'DRENCH STENCH CLENCH QUENCH', 'RETRENCH ENTRENCH'),
  ENSE: f('FENCE SENSE TENSE DENSE HENCE', 'PENCE WHENCE', 'DEFENSE OFFENSE INTENSE IMMENSE EXPENSE'),
  EST: f('BEST NEST REST TEST VEST WEST PEST ZEST CHEST GUEST', 'QUEST CREST', 'REQUEST INVEST SUGGEST DETEST UNREST ARREST'),
  ET: f('SET GET BET NET WET PET JET VET MET', 'DEBT SWEAT YET', 'FORGET REGRET UPSET SILHOUETTE'),
  ESS: f('LESS MESS DRESS PRESS CHESS GUESS', 'BLESS YES STRESS', 'SUCCESS EXCESS DISTRESS ADDRESS DEPRESS EXPRESS IMPRESS'),
  ECK: f('NECK DECK CHECK PECK', 'SPECK WRECK HECK FLECK', 'PAYCHECK'),
  IT: f('BIT HIT SIT FIT KIT PIT SPIT SLIT KNIT', 'GRIT QUIT SPLIT', 'SUBMIT ADMIT COMMIT OMIT'),
  IN: f('BIN FIN PIN WIN TIN SIN GRIN SKIN THIN CHIN SPIN TWIN', 'INN DIN KIN SHIN', 'BEGIN WITHIN VIOLIN'),
  ING: f('SING KING RING WING THING BRING SWING STING SPRING STRING', 'CLING SLING WRING FLING', 'OFFSPRING HAMSTRING'),
  INK: f('PINK SINK THINK BLINK LINK DRINK WINK RINK', 'SHRINK STINK BRINK CLINK MINK', 'RETHINK'),
  ICK: f('STICK BRICK CHICK CLICK KICK LICK PICK QUICK SICK THICK TICK TRICK', 'FLICK WICK NICK SLICK', 'LIPSTICK CANDLESTICK YARDSTICK CHOPSTICK'),
  ILL: f('BILL CHILL DRILL FILL GRILL HILL KILL MILL PILL SKILL SPILL STILL THRILL WILL', 'QUILL SHRILL FRILL', 'UPHILL DOWNHILL WINDMILL MOLEHILL ANTHILL'),
  IFT: f('GIFT LIFT DRIFT SHIFT SWIFT', 'RIFT SIFT THRIFT', 'SHOPLIFT'),
  IM: f('SWIM TRIM GRIM HIM RIM DIM SKIM BRIM SLIM', 'WHIM HYMN PRIM VIM', ''),
  IG: f('PIG BIG DIG FIG JIG WIG TWIG', 'GIG', ''),
  ISH: f('FISH DISH WISH SWISH', '', 'GOLDFISH STARFISH JELLYFISH SHELLFISH CATFISH SWORDFISH'),
  ISS: f('KISS MISS HISS BLISS THIS', 'ABYSS', 'DISMISS AMISS'),
  ISK: f('DISK RISK BRISK WHISK', 'FRISK', ''),
  IST: f('LIST MIST FIST TWIST WRIST', 'KISSED MISSED HISSED', 'EXIST INSIST RESIST PERSIST ASSIST CONSIST'),
  ITCH: f('WITCH PITCH DITCH RICH', 'SWITCH STITCH TWITCH HITCH GLITCH', 'BEWITCH ENRICH'),
  ILT: f('QUILT BUILT GUILT TILT', 'KILT WILT SPILT STILT HILT', 'REBUILT'),
  IMP: f('LIMP CHIMP BLIMP SHRIMP', 'SKIMP WIMP', 'PRIMP CRIMP SCRIMP'),
  INT: f('MINT HINT PRINT TINT LINT', 'SPRINT SQUINT FLINT GLINT STINT', 'FOOTPRINT BLUEPRINT IMPRINT PEPPERMINT'),
  IP: f('SHIP TRIP DIP HIP LIP SIP TIP ZIP CHIP FLIP SLIP DRIP GRIP WHIP SKIP', 'CLIP', 'SPACESHIP BATTLESHIP'),
  IX: f('SIX MIX FIX', 'NIX', 'AFFIX CRUCIFIX'),
  IGHT: f('LIGHT NIGHT FIGHT KITE BITE RIGHT TIGHT MIGHT SIGHT', 'BRIGHT FLIGHT KNIGHT WRITE SITE SPITE QUITE WHITE', 'DELIGHT INSIGHT MIDNIGHT TONIGHT TWILIGHT SPOTLIGHT POLITE EXCITE IGNITE UNITE INVITE DYNAMITE'),
  IDE: f('RIDE SIDE WIDE HIDE SLIDE TIDE', 'GLIDE BRIDE PRIDE GUIDE CRIED TRIED DIED FRIED', 'DECIDE DIVIDE PROVIDE OUTSIDE INSIDE COINCIDE CONFIDE LANDSLIDE'),
  IND: f('FIND MIND KIND BLIND HIND', 'GRIND BIND RIND', 'BEHIND REMIND MANKIND UNWIND'),
  INE: f('LINE FINE MINE NINE PINE DINE SIGN SHINE VINE', 'SPINE TWINE WHINE DIVINE DESIGN', 'SUNSHINE PORCUPINE VALENTINE DEADLINE ENTWINE UNDERLINE'),
  IE: f('SKY FLY TRY CRY DRY FRY BY MY EYE PIE TIE LIE DIE', 'SPY SHY WHY BUY HIGH THIGH SIGH', 'APPLY REPLY SUPPLY DENY ALLY RELY DEFY BUTTERFLY GOODBYE'),
  ICE: f('ICE DICE MICE NICE RICE SLICE', 'PRICE SPICE TWICE VICE THRICE', 'ADVICE DEVICE SACRIFICE PARADISE'),
  IZE: f('SIZE PRIZE RISE WISE EYES LIES TIES', 'SPIES FLIES CRIES', 'SURPRISE DISGUISE EXERCISE ADVISE OTHERWISE COMPRISE'),
  IVE: f('FIVE DIVE HIVE DRIVE JIVE', 'THRIVE ALIVE', 'ARRIVE SURVIVE DEPRIVE REVIVE'),
  IPE: f('PIPE WIPE RIPE TYPE HYPE', 'STRIPE SWIPE GRIPE', 'BAGPIPE OVERRIPE PINSTRIPE STEREOTYPE PROTOTYPE ARCHETYPE'),
  IKE: f('BIKE HIKE LIKE STRIKE SPIKE', 'PIKE TYKE MIKE', 'ALIKE UNLIKE DISLIKE MOTORBIKE HITCHHIKE'),
  IME: f('TIME LIME DIME CLIMB CRIME SLIME', 'RHYME PRIME CHIME GRIME MIME SUBLIME', 'OVERTIME PASTIME SOMETIME DAYTIME LIFETIME BEDTIME'),
  ILE: f('SMILE FILE MILE PILE TILE WHILE', 'STYLE AISLE ISLE VILE', 'AWHILE MEANWHILE CROCODILE WORTHWHILE'),
  IRT: f('SHIRT SKIRT DIRT HURT', 'FLIRT SQUIRT ALERT', 'DESSERT DIVERT INSERT CONCERT'),
  IRL: f('GIRL CURL PEARL SWIRL TWIRL WHIRL', 'HURL UNFURL EARL', 'SCHOOLGIRL COWGIRL'),
  IRM: f('WORM FIRM TERM GERM', 'SQUIRM', 'CONFIRM AFFIRM'),
  URN: f('TURN BURN LEARN EARN FERN', 'CHURN STERN YEARN SPURN', 'RETURN CONCERN SUNBURN HEARTBURN'),
  URSE: f('NURSE PURSE CURSE WORSE VERSE', 'HEARSE TERSE', 'REVERSE UNIVERSE DISPERSE REHEARSE IMMERSE'),
  URD: f('WORD BIRD HERD NERD HEARD', 'BLURRED STIRRED SPURRED', 'ABSURD OVERHEARD MISHEARD'),
  OT: f('HOT POT DOT LOT NOT ROT COT KNOT PLOT SLOT SPOT SHOT TROT', 'BLOT CLOT GOT WATT', 'ROBOT APRICOT MASCOT JACKPOT YACHT HOTSHOT SNAPSHOT'),
  OCK: f('SOCK ROCK CLOCK BLOCK DOCK LOCK KNOCK SHOCK FLOCK STOCK', 'MOCK JOCK', 'PADLOCK ROADBLOCK GRIDLOCK DEADLOCK UNLOCK'),
  OP: f('TOP HOP MOP POP DROP SHOP STOP CROP FLOP CHOP PROP', 'SLOP PLOP', 'LOLLIPOP DESKTOP LAPTOP HILLTOP'),
  OB: f('JOB ROB SOB MOB KNOB', 'BLOB SNOB SLOB COB LOB GOB', 'HOBNOB CORNCOB'),
  OX: f('BOX FOX POX OX', 'LOX SOCKS ROCKS CLOCKS BLOCKS', 'SANDBOX MAILBOX PARADOX ORTHODOX MATCHBOX JUKEBOX'),
  ONG: f('SONG LONG STRONG WRONG GONG', 'PRONG', 'ALONG BELONG LIFELONG'),
  OSS: f('LOSS MOSS TOSS CROSS', 'GLOSS DROSS', 'ACROSS CRISSCROSS'),
  OLD: f('BOLD COLD FOLD GOLD HOLD SOLD TOLD OLD', 'MOLD SCOLD ROLLED STROLLED', 'UNTOLD HOUSEHOLD THRESHOLD MARIGOLD UPHOLD BEHOLD'),
  OLT: f('BOLT COLT JOLT VOLT', 'MOLT REVOLT', 'DEADBOLT'),
  OLE: f('HOLE ROLE POLE BOWL GOAL COAL SOUL ROLL', 'MOLE SOLE WHOLE STROLL SCROLL TOLL TROLL', 'CONTROL CONSOLE PATROL ENROLL TADPOLE LOOPHOLE'),
  OAT: f('BOAT COAT GOAT NOTE VOTE WROTE OAT', 'FLOAT MOAT THROAT QUOTE DOTE', 'PETTICOAT SPEEDBOAT PROMOTE ANTIDOTE DENOTE OVERCOAT LIFEBOAT'),
  OAST: f('TOAST COAST GHOST POST HOST MOST ROAST', 'BOAST', 'SEACOAST GOALPOST LAMPPOST OUTPOST'),
  OAD: f('ROAD LOAD TOAD CODE MODE NODE', 'ODE RODE OWED MOWED SNOWED', 'EXPLODE ERODE ABODE RAILROAD DOWNLOAD UPLOAD'),
  OKE: f('JOKE POKE SMOKE BROKE SPOKE WOKE OAK', 'CHOKE STROKE YOKE CLOAK SOAK', 'AWOKE BACKSTROKE ARTICHOKE INVOKE PROVOKE REVOKE'),
  OPE: f('HOPE ROPE SOAP COPE', 'SLOPE SCOPE DOPE MOPE', 'ANTELOPE PERISCOPE MICROSCOPE TELESCOPE HOROSCOPE KALEIDOSCOPE ENVELOPE'),
  OACH: f('COACH POACH ROACH', 'BROACH', 'APPROACH ENCROACH REPROACH COCKROACH'),
  OSE: f('NOSE ROSE HOSE POSE THOSE CHOSE', 'TOES DOZE FROZE SHOWS BLOWS GROWS FLOWS KNOWS', 'COMPOSE PROPOSE SUPPOSE EXPOSE OPPOSE DISPOSE'),
  ONE: f('BONE CONE PHONE STONE ZONE OWN KNOWN GROWN', 'THRONE TONE DRONE ALONE BLOWN SHOWN THROWN MOAN GROAN', 'TELEPHONE MICROPHONE SAXOPHONE BACKBONE CORNERSTONE HOMEGROWN OVERTHROWN CYCLONE'),
  OWN: f('BROWN CLOWN CROWN DOWN TOWN GOWN FROWN', 'DROWN RENOWN', 'DOWNTOWN UPTOWN HOMETOWN BREAKDOWN COUNTDOWN SHOWDOWN'),
  OH: f('GO NO SO SNOW BLOW KNOW GROW SHOW SLOW LOW', 'GLOW FLOW THROW CROW SEW DOUGH TOE HOE WOE FOE', 'BELOW OVERFLOW ALTHOUGH PLATEAU TABLEAU CHATEAU'),
  OW: f('COW HOW NOW WOW VOW BROW PLOW', 'CHOW ALLOW', 'ANYHOW SOMEHOW ENDOW DISAVOW'),
  OUT: f('OUT SHOUT SCOUT TROUT SPOUT POUT', 'SPROUT DOUBT ABOUT', 'WITHOUT LAYOUT WORKOUT LOOKOUT BLACKOUT HANDOUT KNOCKOUT WIPEOUT'),
  OUSE: f('MOUSE HOUSE LOUSE', 'BLOUSE GROUSE SPOUSE', 'CLUBHOUSE DOGHOUSE GREENHOUSE LIGHTHOUSE WAREHOUSE FIREHOUSE'),
  OUND: f('FOUND SOUND ROUND GROUND POUND HOUND', 'BOUND MOUND ASTOUND', 'AROUND UNDERGROUND BACKGROUND PLAYGROUND SURROUND ABOUND'),
  OUD: f('LOUD PROUD CLOUD CROWD', 'SHROUD ALOUD ALLOWED VOWED PLOWED', 'OVERCROWD DISALLOWED'),
  OUR: f('HOUR SOUR FLOUR', 'TOWER POWER FLOWER SHOWER COWER SCOUR', 'SUNFLOWER CAULIFLOWER WILDFLOWER MAYFLOWER EMPOWER HORSEPOWER'),
  OWL: f('OWL HOWL FOWL', 'TOWEL GROWL PROWL SCOWL JOWL', ''),
  ORE: f('MORE SHORE STORE CORE BORE FOUR DOOR FLOOR ROAR SORE WORE', 'SNORE SCORE CHORE SWORE PORE TORE POUR SOAR ORE', 'ADORE EXPLORE IGNORE BEFORE RESTORE ENCORE SEASHORE GALORE FOLKLORE SYCAMORE DINOSAUR'),
  ORN: f('BORN CORN HORN TORN WORN THORN', 'MORN SCORN SWORN SHORN', 'POPCORN UNICORN ADORN FORLORN'),
  ORT: f('SHORT SPORT COURT FORT SORT PORT', 'SNORT TORT', 'RESORT SUPPORT PASSPORT AIRPORT REPORT TRANSPORT IMPORT'),
  ORM: f('STORM FORM WARM NORM DORM SWARM', 'REFORM INFORM', 'PERFORM UNIFORM CONFORM TRANSFORM'),
  ORSE: f('HORSE FORCE COURSE SOURCE', 'HOARSE', 'DIVORCE REMORSE ENFORCE'),
  OY: f('BOY TOY JOY SOY', 'COY ENJOY EMPLOY ANNOY DECOY', 'DESTROY CONVOY COWBOY TOMBOY CORDUROY'),
  OIL: f('OIL BOIL COIL FOIL SOIL TOIL', 'SPOIL BROIL', 'UNCOIL RECOIL TURMOIL'),
  OIN: f('COIN JOIN LOIN', 'GROIN ADJOIN ENJOIN', 'PURLOIN'),
  OOM: f('ROOM BROOM BLOOM BOOM ZOOM DOOM', 'GLOOM GROOM LOOM TOMB WOMB PLUME FUME', 'BEDROOM CLASSROOM BALLROOM HEIRLOOM ASSUME CONSUME PERFUME COSTUME'),
  OON: f('MOON SOON SPOON NOON TUNE JUNE DUNE', 'PRUNE LOON SWOON BALLOON CARTOON', 'RACCOON LAGOON MAROON MONSOON HARPOON TYPHOON COCOON BASSOON BUFFOON'),
  OOL: f('COOL FOOL POOL SCHOOL TOOL STOOL', 'SPOOL RULE DROOL', 'CARPOOL WHIRLPOOL OVERRULE PRESCHOOL'),
  OOT: f('BOOT ROOT SHOOT FRUIT SUIT HOOT', 'LOOT FLUTE MUTE BRUTE SCOOT', 'SALUTE DISPUTE COMPUTE PURSUIT PARACHUTE RECRUIT'),
  OOF: f('HOOF PROOF', 'SPOOF ALOOF', 'WATERPROOF FIREPROOF BULLETPROOF'),
  OO: f('BLUE GLUE TRUE CLUE TWO ZOO SHOE YOU NEW', 'CREW CHEW GREW FLEW KNEW DUE HUE SCREW THREW STEW', 'KANGAROO SHAMPOO TATTOO BAMBOO CANOE KAZOO CUCKOO'),
  OOK: f('BOOK COOK HOOK LOOK TOOK SHOOK', 'CROOK BROOK NOOK', 'NOTEBOOK COOKBOOK OVERLOOK UNDERTOOK OUTLOOK TEXTBOOK'),
  OOD: f('FOOD MOOD RUDE DUDE', 'BROOD PRUDE SHREWD CRUDE', 'ATTITUDE GRATITUDE ALTITUDE INTRUDE EXCLUDE INCLUDE CONCLUDE'),
  OUP: f('SOUP LOOP HOOP GROUP TROOP', 'SCOOP SWOOP STOOP DROOP SNOOP WHOOP', 'NINCOMPOOP'),
  UCE: f('JUICE GOOSE MOOSE LOOSE', 'SPRUCE TRUCE NOOSE DEUCE', 'REDUCE INDUCE SEDUCE INTRODUCE CABOOSE'),
  UD: f('MUD BUD BLOOD FLOOD', 'STUD THUD SPUD DUD', ''),
  UG: f('BUG HUG JUG MUG RUG TUG PLUG', 'SHRUG SNUG SLUG DUG', 'LADYBUG HUMBUG FIREBUG JITTERBUG EARPLUG'),
  UB: f('CUB PUB RUB TUB CLUB', 'SCRUB SHRUB GRUB STUB HUB SUB', 'NIGHTCLUB'),
  UN: f('SUN FUN RUN BUN ONE SON DONE WON', 'NUN TON STUN SPUN SHUN PUN', 'BEGUN UNDONE OUTRUN OVERDONE'),
  UM: f('GUM HUM DRUM PLUM SUM MUM SOME COME', 'THUMB CRUMB DUMB NUMB STRUM', 'OVERCOME BECOME HUMDRUM'),
  UMP: f('BUMP DUMP JUMP LUMP PUMP', 'STUMP CLUMP PLUMP THUMP SLUMP HUMP TRUMP', 'GRUMP CHUMP FRUMP'),
  UNK: f('JUNK PUNK TRUNK BUNK SUNK', 'SKUNK CHUNK DRUNK FLUNK SPUNK', 'SHRUNK PLUNK CLUNK HUNK MONK'),
  UCK: f('DUCK LUCK TRUCK STUCK BUCK TUCK SUCK', 'MUCK CLUCK PLUCK CHUCK YUCK', 'AMUCK POTLUCK'),
  UST: f('BUST DUST RUST TRUST JUST MUST', 'GUST CRUST THRUST', 'ADJUST ROBUST SAWDUST STARDUST MISTRUST DISGUST UNJUST'),
  UNCH: f('LUNCH BUNCH PUNCH CRUNCH MUNCH', 'HUNCH BRUNCH SCRUNCH', ''),
  UT: f('CUT HUT NUT BUT GUT SHUT', 'JUT RUT STRUT', 'COCONUT PEANUT WALNUT DOUGHNUT CHESTNUT HAZELNUT UNDERCUT SHORTCUT'),
  UFF: f('PUFF STUFF ROUGH TOUGH', 'ENOUGH FLUFF BLUFF CUFF HUFF SCUFF', 'HANDCUFF REBUFF GRUFF'),
  UDGE: f('JUDGE FUDGE BUDGE NUDGE', 'SMUDGE GRUDGE TRUDGE SLUDGE', 'DRUDGE ADJUDGE PREJUDGE MISJUDGE'),
  UP: f('CUP PUP UP', 'SUP', 'BUTTERCUP TEACUP EGGCUP'),
  UMBLE: f('TUMBLE JUMBLE HUMBLE RUMBLE', 'MUMBLE GRUMBLE STUMBLE CRUMBLE FUMBLE BUMBLE', ''),
  ATTER: f('BATTER MATTER CHATTER PATTER', 'SCATTER SHATTER FLATTER LATTER CLATTER', 'SPLATTER TATTER NATTER'),
  UTTER: f('BUTTER GUTTER UTTER MUTTER CUTTER', 'SHUTTER STUTTER CLUTTER FLUTTER SPUTTER', ''),
  ITTER: f('LITTER BITTER SITTER FITTER', 'GLITTER TWITTER CRITTER', 'BABYSITTER'),
  OG_AO: f('DOG LOG BLOG', '', 'BULLDOG'),
  OG_AA: f('FROG HOG JOG SMOG CLOG', 'SLOG GROG FLOG', 'HEDGEHOG')
};

const LEGACY_CORE = ["CAT","NIGHT","CAKE","RING","BOAT","BEAR","TRAIN","CLOCK","STAR","CHAIR","BLUE","BONE","SAND","DOG","TREE","SUN","MOON","FISH","DUCK","PEN","CUP","BED","PIG","FOX","HOUSE","CAR","DOOR","BOOK","GAME","BALL","FIRE","GOLD","ICE","SNOW","WIND","CLOUD","RAIN","STORM","WAVE","HILL","ROCK","ROAD","PATH","BRIDGE","TOWN","STREET","PARK","SHOP","FARM","BARN","BIRD","COW","HORSE","SHEEP","GOAT","DEER","WOLF","SNAKE","FROG","CRAB","WHALE","SHARK","SEAL","BEE","ANT","FLY","WORM","SPIDER","EYE","NOSE","EAR","MOUTH","HAND","FOOT","LEG","ARM","HEART","MIND","TIME","DAY","WEEK","MONTH","YEAR","SPRING","SUMMER","FALL","WINTER","MORNING","NOON","EVENING","DAWN","DUSK","RED","GREEN","YELLOW","BLACK","WHITE","GRAY"];
const LEGACY_LONG = ["ABDOMEN","ASTRONAUT","BICYCLE","BUTTERFLY","CALENDAR","CHOCOLATE","DIAMOND","ELEPHANT","FESTIVAL","GALAXY","HARMONY","HORIZON","INSTRUMENT","JUNGLE","KANGAROO","LAVENDER","MICROSCOPE","NECTAR","OXYGEN","PENGUIN","QUARTER","RADIATOR","SYMPHONY","TELESCOPE","UMBRELLA","VOLCANO","WATERFALL","XYLOPHONE","YOGURT","ZEPPELIN","ACADEMY","BACTERIA","CABINET","DAFFODIL","ECONOMY","FACTORY","GEOMETRY","HELICOPTER","ILLUSION","JOURNAL","KEYBOARD","LABORATORY","MACHINERY","NOVELIST","ORCHESTRA","PARACHUTE","QUADRANT","REPTILE","SATELLITE","THERMOMETER","UNIVERSE","VACUUM","WILDERNESS","YACHT","ZOOLOGY","ALGEBRA","BROCCOLI","CAPITAL","DINOSAUR","ELEVATOR","FURNITURE","GOVERNOR","HOSPITAL","INVENTOR","JUSTICE","KINETIC","LIBRARY","MONUMENT","NARRATIVE","OASIS","PYRAMID","QUESTION","RESTAURANT","STADIUM","TRIANGLE","UTENSIL","VEHICLE","WEATHER","YIELD","ZEBRA","ARCHITECT","BALCONY","CAMERA","DOCUMENT","ENVELOPE","FEATHER","GALLERY","HERITAGE","ISLAND","JACKET","KITCHEN","LUGGAGE","MEDICINE","NETWORK","OFFICER","PASSENGER","QUALITY","RECIPE","SCIENTIST","TEACHER"];

const WORD_FAMILIES = { core: LEGACY_CORE, longWords: LEGACY_LONG };
const TIER_OF = new Map();
const wordToFamily = new Map();
for (const [family, tiers] of Object.entries(FAMILY_TIERS)) {
  WORD_FAMILIES[family] = [...tiers.easy, ...tiers.medium, ...tiers.hard];
  for (const tier of ['easy', 'medium', 'hard']) {
    for (const word of tiers[tier]) {
      if (wordToFamily.has(word)) throw new Error(`Duplicate rhyme-bank word: ${word}`);
      wordToFamily.set(word, family);
      TIER_OF.set(word, tier);
    }
  }
}
const WORD_BANK = [...new Set(Object.values(WORD_FAMILIES).flat())];
const TARGET_POOLS = {
  easy: [...TIER_OF].filter(([, tier]) => tier === 'easy').map(([word]) => word),
  normal: [...TIER_OF].filter(([, tier]) => tier !== 'hard').map(([word]) => word),
  hard: [...TIER_OF].filter(([, tier]) => tier !== 'easy').map(([word]) => word)
};
const QUALITY_WORDS = TARGET_POOLS.normal;
const RECENT_TARGET_LIMIT = 18;
const RECENT_FAMILY_LIMIT = 8;
const HISTORY_KEY = 'rhymeMatchTargets';

const normalize = normalizeWord;
function familyOf(word) {
  const upper = normalize(word);
  return wordToFamily.get(upper) || `other:${upper.slice(-3)}`;
}
function getRhymes(target, { tier = null, limit = 0 } = {}) {
  const upper = normalize(target);
  const tiers = FAMILY_TIERS[wordToFamily.get(upper)];
  if (!tiers || (tier !== null && !['easy', 'medium', 'hard'].includes(tier))) return [];
  const order = tier === null ? ['easy', 'medium', 'hard'] : [tier];
  const rhymes = order.flatMap(level => tiers[level]).filter(word => word !== upper);
  return Number.isInteger(limit) && limit > 0 ? rhymes.slice(0, limit) : rhymes;
}
// A false result means unknown to this finite bank; it never invalidates a guess.
function isKnownRhyme(target, guess) {
  const upper = normalize(target);
  const other = normalize(guess);
  return upper !== other && Boolean(wordToFamily.get(upper)) && wordToFamily.get(upper) === wordToFamily.get(other);
}
function loadTargetHistory(fallback = { words: [], families: [] }) {
  try {
    const saved = localStorage.getItem(HISTORY_KEY);
    if (!saved) return fallback;
    const data = JSON.parse(saved);
    return {
      words: Array.isArray(data.words) ? data.words.filter(w => typeof w === 'string').map(normalize).slice(-RECENT_TARGET_LIMIT) : [],
      families: Array.isArray(data.families) ? data.families.filter(w => typeof w === 'string').slice(-RECENT_FAMILY_LIMIT) : []
    };
  } catch { return fallback; }
}
let targetHistory = loadTargetHistory();
function rememberTarget(word) {
  const upper = normalize(word);
  if (!upper) return;
  targetHistory = loadTargetHistory(targetHistory);
  targetHistory.words = [...targetHistory.words.filter(w => w !== upper), upper].slice(-RECENT_TARGET_LIMIT);
  targetHistory.families = [...targetHistory.families, familyOf(upper)].slice(-RECENT_FAMILY_LIMIT);
  try { localStorage.setItem(HISTORY_KEY, JSON.stringify(targetHistory)); } catch { /* Private browsing may disable storage. */ }
}
function pickFromFamilies(words) {
  const byFamily = new Map();
  for (const word of words) {
    const family = wordToFamily.get(word);
    if (!byFamily.has(family)) byFamily.set(family, []);
    byFamily.get(family).push(word);
  }
  const families = [...byFamily.keys()];
  const family = families[Math.floor(Math.random() * families.length)];
  const options = byFamily.get(family);
  return options[Math.floor(Math.random() * options.length)];
}
function pickTarget(level = 'normal') {
  targetHistory = loadTargetHistory(targetHistory);
  const pool = TARGET_POOLS[level] || TARGET_POOLS.normal;
  const freshWords = pool.filter(word => !targetHistory.words.includes(word));
  const choices = freshWords.filter(word => !targetHistory.families.includes(wordToFamily.get(word)));
  const fallback = pool.filter(word => !targetHistory.families.includes(wordToFamily.get(word)));
  return pickFromFamilies(choices.length ? choices : freshWords.length ? freshWords : fallback.length ? fallback : pool);
}

const ONE_SYLLABLE_WORDS = new Set([
  'AID AIM AIR ARM ART BACK BAD BAG BAIT BAKE BALK BALL BAN BAND BANG BANK BAR BARD BARE BARK BASE BASH BAT BATCH BEACH BEAD BEAK BEAM BEAN BEAR BEAT BED BEE BEECH BEER BEES BEET BELL BELT BENCH BEND BENT BEST BET BIG BIKE BILL BIN BIND BIRD BIT BITE BLAB BLACK BLADE BLAME BLANK BLAZE BLEAK BLEND BLESS BLIMP BLIND BLINK BLISS BLOB BLOCK BLOCKS BLOG BLOOD BLOOM BLOT BLOUSE BLOW BLOWN BLOWS BLUE BLUFF BLURRED BOAST',
  'BOAT BOIL BOLD BOLT BONE BOOK BOOM BOOT BORE BORN BOUGHT BOUND BOWL BOX BOY BRACE BRAG BRAID BRAIN BRAKE BRAND BRASS BRAT BRAVE BRAWN BREACH BREAD BREAK BREED BREEZE BRICK BRIDE BRIEF BRIGHT BRIM BRING BRINK BRISK BROACH BROIL BROKE BROOD BROOK BROOM BROUGHT BROW BROWN BRUNCH BRUTE BUCK BUD BUDGE BUG BUILT BUMP BUN BUNCH BUNK BURN BUST BUT BUY BY CAB CAKE CALL CAME CAN CANE CAP CAR CARD CARE CART CASE CASH CAT CATCH CAUGHT CAVE',
  'CEASE CELL CENT CHAIN CHAIR CHALK CHANCE CHANT CHAP CHARM CHART CHASE CHAT CHEAP CHEAT CHECK CHEEK CHEER CHEESE CHESS CHEST CHEW CHICK CHIEF CHILL CHIME CHIMP CHIN CHIP CHOKE CHOP CHORE CHOSE CHOW CHUCK CHUMP CHUNK CHURN CLAD CLAIM CLAM CLAN CLANG CLAP CLASH CLASS CLAW CLAY CLEAN CLEAR CLENCH CLICK CLIMB CLING CLINK CLIP CLOAK CLOCK CLOCKS CLOG CLOT CLOUD CLOWN CLUB CLUCK CLUE CLUMP CLUNK COACH COAL COAST COAT COB CODE COIL COIN COLD COLT COME CONE',
  'COOK COOL COPE CORE CORN COT COURSE COURT COW COY CRAB CRACK CRANE CRANK CRASH CRATE CRAVE CRAZE CREAM CREED CREEK CREEP CREST CREW CRIED CRIES CRIME CRIMP CROOK CROP CROSS CROW CROWD CROWN CRUDE CRUMB CRUNCH CRUST CRY CUB CUFF CUP CURL CURSE CUT CZAR DAB DAD DAM DANCE DARE DARK DART DASH DATE DAWN DAY DAZE DEAD DEAL DEAR DEBT DECK DEEP DEER DEN DENSE DENT DEUCE DICE DIE DIED DIG DIM DIME DIN DINE DIP DIRT DISH',
  'DISK DITCH DIVE DOCK DOG DONE DOOM DOOR DOPE DORM DOT DOTE DOUBT DOUGH DOWN DOZE DRAB DRAG DRAIN DRANK DRAW DRAWN DREAM DRENCH DRESS DRIFT DRILL DRINK DRIP DRIVE DRONE DROOL DROOP DROP DROSS DROWN DRUDGE DRUM DRUNK DRY DUCK DUD DUDE DUE DUG DUMB DUMP DUNE DUST DWELL DWELT EAR EARL EARN EAT EIGHT END EVE EYE EYES FACE FAD FADE FAIL FAIR FALL FAME FAN FANG FAR FARM FAT FAULT FAWN FEAR FED FEED FEEL FEET FELL',
  'FELT FEN FENCE FERN FIG FIGHT FILE FILL FIN FIND FIRM FISH FIST FIT FIVE FIX FLAB FLAG FLAIL FLAKE FLAME FLAP FLARE FLASH FLAT FLAW FLEA FLEAS FLECK FLED FLEE FLEECE FLEW FLICK FLIES FLIGHT FLING FLINT FLIP FLIRT FLOAT FLOCK FLOG FLOOD FLOOR FLOP FLOW FLOWS FLUFF FLUNK FLUTE FLY FOE FOIL FOLD FOOD FOOL FORCE FORM FORT FOUGHT FOUND FOUR FOWL FOX FRAME FRANK FREE FREED FREEZE FREIGHT FRIED FRIEND FRILL FRISK FROG FROWN FROZE FRUIT FRUMP',
  'FRY FUDGE FUME FUN GAIN GALE GAME GANG GAP GATE GAVE GAZE GEAR GEEK GERM GET GHOST GIFT GIG GIRL GLAD GLADE GLANCE GLARE GLASS GLAZE GLEAM GLEE GLIDE GLINT GLITCH GLOOM GLOSS GLOW GLUE GNAT GNAW GO GOAL GOAT GOB GOLD GONG GOOSE GOT GOWN GRAB GRACE GRADE GRAIN GRAND GRANT GRASS GRATE GRAVE GRAY GRAZE GREASE GREAT GREED GREEN GREET GREW GRIEF GRIEVE GRILL GRIM GRIME GRIN GRIND GRIP GRIPE GRIT GROAN GROG GROIN GROOM GROUND GROUP GROUSE',
  'GROW GROWL GROWN GROWS GRUB GRUDGE GRUFF GRUMP GUARD GUESS GUEST GUIDE GUILT GUM GUST GUT HAD HAIR HALL HALT HAM HAND HANG HARD HARM HAT HATCH HATE HAY HAZE HEAD HEAP HEARD HEARSE HEART HEAT HEAVE HECK HEEL HELL HEN HENCE HERD HIDE HIGH HIKE HILL HILT HIM HIND HINT HIP HISS HISSED HIT HITCH HIVE HOARSE HOE HOG HOLD HOLE HOOF HOOK HOOP HOOT HOP HOPE HORN HORSE HOSE HOST HOT HOUND HOUSE HOW HOWL HUB HUE HUFF',
  'HUG HUM HUMP HUNCH HUNK HURL HURT HUT HYMN HYPE ICE INN ISLE JAB JACK JAIL JAM JAR JAW JEEP JET JIG JIVE JOB JOCK JOG JOIN JOKE JOLT JOWL JOY JUDGE JUG JUICE JUMP JUNE JUNK JUST JUT KEEN KEEP KEY KICK KILL KILT KIN KIND KING KISS KISSED KIT KITE KNAVE KNEE KNEEL KNEES KNELT KNEW KNIGHT KNIT KNOB KNOCK KNOT KNOW KNOWN KNOWS LAB LACE LACK LAD LAID LAKE LAME LAND LANE LAP LARD LARK LASS LATCH',
  'LATE LAW LAWN LEAF LEAK LEAN LEAP LEARN LEASE LEAVE LEECH LEND LENT LESS LICK LIE LIES LIFT LIGHT LIKE LIME LIMP LINE LINK LINT LIP LIST LOAD LOB LOCK LOG LOIN LONG LOOK LOOM LOON LOOP LOOSE LOOT LOSS LOT LOUD LOUSE LOW LOX LUCK LUMP LUNCH MAD MADE MAID MAIL MAIN MAKE MALL MALT MAN MAP MARK MASH MASS MAT MATCH MATE MAY MAZE MEAL MEAN MEANT MEAT MEET MELT MEN MEND MESS MET MICE MIGHT MIKE MILE',
  'MILL MIME MIND MINE MINK MINT MISS MISSED MIST MIX MOAN MOAT MOB MOCK MODE MOLD MOLE MOLT MONK MOOD MOON MOOSE MOP MOPE MORE MORN MOSS MOST MOUND MOUSE MOWED MUCK MUD MUG MUM MUNCH MUST MUTE MY NAB NAG NAIL NAME NAP NEAR NEAT NECK NEED NERD NEST NET NEW NICE NICK NIGHT NINE NIX NO NODE NOOK NOON NOOSE NORM NOSE NOT NOTE NOW NUDGE NUMB NUN NURSE NUT OAK OAT ODE OIL OLD ONE ORE OUGHT',
  'OUT OWED OWL OWN OX PACE PACK PAD PAID PAIN PAIR PALE PAN PANG PANT PARK PART PASS PAT PATCH PAVE PAW PAWN PAY PEA PEACE PEACH PEAK PEAL PEAR PEARL PEAS PECK PEEL PEEP PEER PELT PEN PENCE PEST PET PHONE PHRASE PICK PIE PIECE PIG PIKE PILE PILL PIN PINE PINK PIPE PIT PITCH PLACE PLAID PLAIN PLAN PLANE PLANK PLANT PLATE PLAY PLEA PLEASE PLOP PLOT PLOW PLOWED PLUCK PLUG PLUM PLUME PLUMP PLUNK POACH POKE POLE',
  'POOL POP PORE PORT POSE POST POT POUND POUR POUT POX PRAISE PRANCE PRANK PRAWN PRAY PREACH PREEN PRESS PREY PRICE PRIDE PRIM PRIME PRIMP PRINT PRIZE PRONG PROOF PROP PROUD PROWL PRUDE PRUNE PUB PUFF PUMP PUN PUNCH PUNK PUP PURSE QUACK QUAKE QUEEN QUENCH QUEST QUICK QUILL QUILT QUIT QUITE QUOTE RACE RACK RAG RAID RAIN RAISE RAKE RAM RAN RANG RANK RANT RASH RAT RAVE REACH REAL RED REEF REEL REIGN RENT REST RHYME RICE RICH RIDE',
  'RIFT RIGHT RIM RIND RING RINK RIPE RISE RISK ROACH ROAD ROAR ROAST ROB ROCK ROCKS RODE ROLE ROLL ROLLED ROOM ROOT ROPE ROSE ROT ROUGH ROUND RUB RUDE RUG RULE RUN RUST RUT SACK SAD SAG SAID SAIL SALT SAME SAND SANG SANK SASH SASS SAT SAVE SAW SAY SCAB SCALE SCAM SCAN SCANT SCAR SCARE SCENE SCENT SCHEME SCHOOL SCOLD SCOOP SCOOT SCOPE SCORE SCORN SCOUT SCOWL SCRAP SCRATCH SCREAM SCREECH SCREEN SCREW SCRIMP SCROLL SCRUB SCRUNCH SCUFF',
  'SEA SEAL SEAM SEAT SEE SEED SEEK SEEN SEIZE SELL SEND SENSE SET SEW SHACK SHADE SHAG SHAKE SHAM SHAME SHARD SHARE SHARK SHAVE SHEAF SHED SHEEN SHEEP SHEET SHELL SHIFT SHIN SHINE SHIP SHIRT SHOCK SHOE SHOOK SHOOT SHOP SHORE SHORN SHORT SHOT SHOUT SHOW SHOWN SHOWS SHRANK SHREWD SHRILL SHRIMP SHRINK SHROUD SHRUB SHRUG SHRUNK SHUN SHUT SHY SICK SIDE SIFT SIGH SIGHT SIGN SIN SING SINK SIP SIT SITE SIX SIZE SKATE SKI SKILL SKIM SKIMP SKIN',
  'SKIP SKIRT SKUNK SKY SLAB SLAM SLANG SLANT SLAP SLASH SLATE SLED SLEEP SLEET SLEEVE SLEIGH SLICE SLICK SLIDE SLIM SLIME SLING SLIP SLIT SLOB SLOG SLOP SLOPE SLOT SLOW SLUDGE SLUG SLUMP SMACK SMALL SMART SMASH SMEAR SMELL SMELT SMILE SMOG SMOKE SMUDGE SNACK SNAG SNAIL SNAKE SNAP SNATCH SNEAK SNEEZE SNOB SNOOP SNORE SNORT SNOW SNOWED SNUG SO SOAK SOAP SOAR SOB SOCK SOCKS SOIL SOLD SOLE SOME SON SONG SOON SORE SORT SOUGHT SOUL SOUND SOUP SOURCE',
  'SOY SPACE SPADE SPAM SPAN SPANK SPAR SPARE SPARK SPAWN SPEAK SPEAR SPECK SPED SPEECH SPEED SPELL SPEND SPENT SPICE SPIES SPIKE SPILL SPILT SPIN SPINE SPIT SPITE SPLASH SPLAT SPLIT SPOIL SPOKE SPOOF SPOOL SPOON SPORT SPOT SPOUSE SPOUT SPRAIN SPRAY SPREAD SPREE SPRINT SPROUT SPRUCE SPUD SPUN SPUNK SPURN SPURRED SPY SQUARE SQUEAK SQUEAL SQUEEZE SQUINT SQUIRM SQUIRT STACK STAG STAIN STAIR STAKE STALE STALK STALL STANCE STAND STAR STARE STARK START STASH STATE STAY STEAK STEAL STEAM',
  'STEEL STEEP STEER STENCH STERN STEW STICK STILL STILT STING STINK STINT STIRRED STITCH STOCK STONE STOOL STOOP STOP STORE STORM STRAIGHT STRAND STRAP STRAW STREAK STREAM STREET STRESS STRIKE STRING STRIPE STROKE STROLL STROLLED STRONG STRUM STRUT STUB STUCK STUD STUFF STUMP STUN STYLE SUB SUCK SUIT SUM SUN SUNK SUP SWAM SWARM SWAY SWEAR SWEAT SWEEP SWEET SWELL SWIFT SWIM SWING SWIPE SWIRL SWISH SWITCH SWOON SWOOP SWORE SWORN TAB TACK TAG TAIL TAKE TALE TALK TALL TAME',
  'TAN TANK TAP TAR TART TAUGHT TEA TEACH TEAM TEASE TEEN TELL TEN TEND TENSE TENT TERM TERSE TEST THANK THAT THATCH THAW THEME THEN THERE THEY THICK THIEF THIEVE THIGH THIN THING THINK THIS THORN THOSE THOUGHT THREAD THREE THREW THRICE THRIFT THRILL THRIVE THROAT THRONE THROW THROWN THRUST THUD THUMB THUMP TICK TIDE TIE TIES TIGHT TILE TILT TIME TIN TINT TIP TOAD TOAST TOE TOES TOIL TOLD TOLL TOMB TON TONE TOOK TOOL TOP TORE TORN TORT',
  'TOSS TOUGH TOWN TOY TRACE TRACK TRADE TRAIL TRAIN TRAM TRANCE TRAP TRASH TRAY TREAT TREE TREES TRENCH TREND TRICK TRIED TRIM TRIP TROLL TROOP TROT TROUT TRUCE TRUCK TRUDGE TRUE TRUMP TRUNK TRUST TRY TUB TUCK TUG TUNE TURN TWEAK TWEED TWEET TWICE TWIG TWIN TWINE TWIRL TWIST TWITCH TWO TYKE TYPE UP VAN VAT VAULT VEIN VENT VERSE VEST VET VICE VILE VIM VINE VOLT VOTE VOW VOWED WADE WAG WAIT WAKE WALK WALL WARM WATT WAVE WAY',
  'WEAK WEAR WEAVE WED WEED WEEK WEIGH WEIGHT WELL WENT WEST WET WHACK WHALE WHEAT WHEEL WHEEZE WHEN WHENCE WHERE WHILE WHIM WHINE WHIP WHIRL WHISK WHITE WHOLE WHOOP WHY WICK WIDE WIG WILL WILT WIMP WIN WING WINK WIPE WISE WISH WITCH WOE WOKE WOMB WON WORD WORE WORM WORN WORSE WOW WRAP WRECK WREN WRENCH WRING WRIST WRITE WRONG WROTE WROUGHT YACHT YANK YARD YAWN YEAR YEARN YELL YEN YES YET YOKE YOU YUCK ZAP ZEN ZEST ZIP',
  'ZONE ZOO ZOOM',
].join(' ').split(' '));
const TWIST_TAGS = {
  food:'CAKE CUPCAKE PANCAKE MILKSHAKE STEAK RICE SPICE SLICE MEAT WHEAT TREAT APRICOT CORN POPCORN PLUM GUM SOUP JUICE CHEESE BREAD FRUIT PEACH PEA BEAN BEET SHRIMP LUNCH BRUNCH FUDGE PEANUT WALNUT COCONUT DOUGHNUT CHESTNUT HAZELNUT TANGERINE ARTICHOKE LEMONADE GINGERBREAD TOAST BUTTER SALT',
  animal:'BAT RAT GNAT WOMBAT MUSKRAT SNAKE MOUSE GROUSE MOLE TADPOLE DEER REINDEER TROUT OWL LARK SHARK SKUNK CHICK COW CROW CRAB PIG DOG FROG HOG GOAT WHALE SHEEP HEN BEAR CHIMP SHRIMP KANGAROO DINOSAUR HEDGEHOG BULLDOG RACCOON PORCUPINE GOLDFISH STARFISH JELLYFISH CATFISH SWORDFISH BUTTERFLY LADYBUG COCKROACH MOOSE GOOSE FLEA MICE',
  object:'HAT MAT DOORMAT TRAY CLAY RAKE BRAKE STAKE FRAME BROOM PHONE STONE BRICK STICK CLOCK SOCK BLOCK BAG FLAG MUG RUG JUG CUP PEN KEY BELL DRUM KNOB TOOL SPOON BOOK BOOT SUIT TUB BIN PIN PAD LOCK PADLOCK NOTEBOOK COOKBOOK LAPTOP DESKTOP CANDLESTICK CHOPSTICK HANDBAG SANDBAG SUITCASE BAGPIPE MICROSCOPE TELESCOPE',
  place:'LAKE SHORE STORE PARK LANDMARK ROOM BEDROOM CLASSROOM BALLROOM DOWNTOWN UPTOWN HOMETOWN SEASHORE AIRPORT PORT COURT FORT TOWN HOUSE CLUBHOUSE DOGHOUSE GREENHOUSE LIGHTHOUSE WAREHOUSE FIREHOUSE SCHOOL POOL YARD BACKYARD PLAYGROUND SUBWAY LANE ISLE COAST SEACOAST',
  job:'KING GROOM REFEREE ENGINEER VOLUNTEER PIONEER NURSE SCOUT JUDGE COACH COWBOY BABYSITTER CHIEF HOST',
  nature:'LAKE FLAME RAIN CLOUD STORM WAVE STAR ROCK TREE SNOW HILL BREEZE THORN DAWN SKY SEA MOON SUN LEAF FLOWER SUNFLOWER WILDFLOWER MAYFLOWER SAND SHORE CAVE GRASS STONE DUNE MOSS FERN SUNSHINE',
  sound:'BELL COWBELL DOORBELL YELL HOWL GROWL SQUEAK BANG CLANG SONG GONG HUM DRUM BOOM SHOUT SNORE THUD THUMP SPLASH CRASH CLICK QUACK CLUCK SNEEZE WHEEZE ROAR TWEET HOOT SIGH',
  clothing:'HAT COAT GOWN SHIRT SKIRT VEST SOCK BOOT SUIT CLOAK OVERCOAT PETTICOAT SLEEVE',
  travel:'TRAIN PLANE BOAT ROAD RUNWAY SUBWAY PASSPORT AIRPORT PORT CAR CAB VAN SHIP SPACESHIP BATTLESHIP SPEEDBOAT LIFEBOAT AIRPLANE TAXICAB CARAVAN BIKE MOTORBIKE YACHT TRUCK RIDE JEEP',
  celebration:'CAKE CUPCAKE BIRTHDAY HOLIDAY HOORAY JUBILEE GIFT CROWN DANCE PARADE BALLOON LEMONADE',
  tiny:'GNAT BUG COIN SEED DICE PEA DOT CRUMB SPECK GRAIN FLEA BIT',
  spooky:'NIGHT MIDNIGHT GLOOM DOOM GHOST CURSE DARK WITCH BEWITCH BAT TOMB',
  action:'PLAY STAY PRAY SING BRING SWING FLY TRY JUMP BUMP CLAP SNAP TAP DRAW SAW WALK TALK TURN BURN SHOUT SWIM SKIP HIKE RIDE SLIDE CATCH THROW KICK RUN DANCE CLIMB HOP SPIN TWIRL DIVE',
  feeling:'JOY GLEE DELIGHT SHAME DESPAIR HOPE FEAR SCARE GLAD SAD MAD PRIDE GRIEF BLISS',
  funny:'JOKE CLOWN PRANK WIG SPLAT',
  party:'CAKE CUPCAKE PANCAKE MILKSHAKE GAME HAT CROWN GIFT JOKE BALLOON LEMONADE DANCE SONG'
};
const TWIST_TAG_LABELS = {
  food:'something edible', animal:'an animal', object:'an object you could use', place:'a place', job:'a job or role', nature:'something from nature', sound:'a sound or something noisy', clothing:'something you could wear', travel:'something linked to travel', celebration:'something at a celebration', tiny:'something tiny', spooky:'something spooky', action:'an action', feeling:'a feeling', funny:'something funny', party:'something you could bring to a party'
};

const TWIST_CHALLENGES = [
  ...Array.from({ length: 8 }, (_, i) => ({ id: `length-${i + 3}`, text: `Use exactly ${i + 3} letters.`, test: word => word.length === i + 3 })),
  { id: 'short', text: 'Use a short rhyme: 3–5 letters.', test: word => word.length >= 3 && word.length <= 5 },
  { id: 'long', text: 'Use a long rhyme: at least 8 letters.', test: word => word.length >= 8 },
  { id: 'one-syllable', text: 'Use a one-syllable rhyme.', test: word => ONE_SYLLABLE_WORDS.has(word) },
  { id: 'verb', text: 'Use a verb: something a person can do.', test: word => TWIST_TAGS.action.split(' ').includes(word) },
  { id: 'ends-in-s', text: 'Use a word ending in S.', test: word => word.endsWith('S') && !word.endsWith('SS') },
  ...'AEIOU'.split('').map(letter => ({ id: `contains-${letter}`, text: `Use a rhyme containing the letter ${letter}.`, test: word => word.includes(letter) })),
  ...'BCDFGHJKLMNPRSTW'.split('').map(letter => ({ id: `starts-${letter}`, text: `Use a rhyme beginning with ${letter}.`, test: word => word.startsWith(letter) })),
  ...Object.entries(TWIST_TAGS).map(([id, words]) => {
    const tagged = new Set(words.split(' ').filter(word => wordToFamily.has(word)));
    return { id: `category-${id}`, text: `Use ${TWIST_TAG_LABELS[id]}.`, test: word => tagged.has(word) };
  })
];
function pickTwistChallenge(target, history = []) {
  const upper = normalize(target);
  const rhymes = getRhymes(upper);
  const eligible = TWIST_CHALLENGES.filter(challenge => rhymes.filter(challenge.test).length >= 2);
  if (!eligible.length) return null;
  const recent = Array.isArray(history) ? history : [];
  const fresh = eligible.filter(challenge => !recent.includes(challenge.id));
  const choices = fresh.length ? fresh : eligible;
  const chosen = choices[Math.floor(Math.random() * choices.length)];
  return { id: chosen.id, text: chosen.text };
}

export {
  WORD_FAMILIES, WORD_BANK, QUALITY_WORDS,
  FAMILY_TIERS, TIER_OF, TARGET_POOLS,
  familyOf, getRhymes, isKnownRhyme,
  rememberTarget, pickTarget, pickTwistChallenge
};
